<?php
// Seed element_methods for Historia ya Tanzania na Maadili Form I (elements 95-145)
require __DIR__ . '/../config/db.php';
$db = getDB();
$db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

$ins = $db->prepare("INSERT INTO element_methods
    (element_id,method_id,stage,time_minutes,teaching_activity,learning_activity,assessment_criteria)
    VALUES (?,?,?,?,?,?,?)");

// method_ids: 5=Brainstorming,7=Case Study,1=Demonstration,11=Field Visit,
// 2=Group Discussion,4=Hands-on,9=Practical,8=Project,3=Q&A,12=Research,10=Role Play,6=Think-Pair-Share

$data = [

// ── Sura ya Kwanza: Utangulizi wa Historia ────────────────────────────────────

// 95: Eleza maana ya Historia na umuhimu wake
[95,5,'introduction',5,
 'Bunguabongo: Ongoza wanafunzi kubungua bongo kwa kuuliza: "Historia ni nini? Kwa nini tunajifunza Historia?"',
 'Toa mawazo yao juu ya maana ya Historia na kwa nini ni muhimu kujifunza.',
 'Wanafunzi wanaweza kutoa maelezo ya awali ya Historia.'],
[95,2,'development',20,
 'Ongoza majadiliano ya vikundi kwa kutumia matini kuhusu maana ya Historia, tofauti kati ya Historia na hadithi za kimapokeo, na umuhimu wake katika maisha ya kila siku.',
 'Jadili katika vikundi maana ya Historia na umuhimu wake. Wasilisha muhtasari darasani.',
 'Maana ya Historia na umuhimu wake katika maisha ya kila siku vimeelezwa kwa usahihi.'],
[95,2,'design',10,
 'Ongoza wanafunzi katika vikundi vyao waorodheshe matukio ya kihistoria yanayowagusa na umuhimu wa kuyajua.',
 'Orodhesha matukio 3 ya kihistoria yanayogusa maisha yao na eleza umuhimu wa kuyajua.',
 'Matukio ya kihistoria yanayohusiana na maisha ya sasa yametambuliwa kwa usahihi.'],
[95,3,'realisation',5,
 'Kila mwanafunzi aeleze kwa sentensi mbili maana ya Historia na sababu moja ya kwa nini ni muhimu kusoma Historia.',
 'Andika sentensi mbili: maana ya Historia na sababu moja ya umuhimu wake.',
 'Maana ya Historia imeelezwa kwa usahihi na sababu ya umuhimu imebainishwa.'],

// 96: Tofautisha Historia na hadithi za kimapokeo
[96,3,'introduction',5,
 'Simulia hadithi fupi ya kimapokeo kisha uliza: Je, hii ni Historia? Inafananaje na Historia? Inatofautianaje?',
 'Sikiliza hadithi na jaribu kutofautisha kati ya hadithi ya kimapokeo na Historia.',
 'Wanafunzi wanaweza kubainisha tofauti moja kati ya Historia na hadithi.'],
[96,2,'development',20,
 'Ongoza majadiliano ya kikundi kulinganisha vipengele vya Historia (ukweli unaothibitishwa na vyanzo) na hadithi za kimapokeo (simulizi zilizopitishwa kwa mdomo).',
 'Jadili na kuandika vipengele vya Historia na vya hadithi za kimapokeo katika jedwali la ulinganisho.',
 'Tofauti kati ya Historia na hadithi za kimapokeo zimebainishwa kwa usahihi.'],
[96,6,'design',10,
 'Fikiri-andika-jozisha-shirikisha: Kila mwanafunzi aandike tofauti tatu kati ya Historia na hadithi, kisha ajadili na mwenzake.',
 'Andika tofauti 3, jozisha na mwenzako, kisha shirikishana na darasa.',
 'Tofauti sahihi tatu kati ya Historia na hadithi za kimapokeo zimebainishwa.'],
[96,3,'realisation',5,
 'Kila mwanafunzi aeleze kwa maneno yake tofauti kuu mbili kati ya Historia na hadithi za kimapokeo.',
 'Andika tofauti mbili kuu kati ya Historia na hadithi za kimapokeo.',
 'Tofauti mbili sahihi kati ya Historia na hadithi zimebainishwa.'],

// 97: Tambua na ueleze vyanzo mbalimbali vya Historia
[97,5,'introduction',5,
 'Onyesha picha au vitu halisi (chombo cha zamani, ramani, kitabu cha zamani). Uliza: Vitu hivi vinaweza kutusaidia kujua nini kuhusu Historia?',
 'Angalia vitu vilivyoonyeshwa na pendekeza jinsi vinavyoweza kutoa habari za kihistoria.',
 'Wanafunzi wanaweza kubainisha angalau chanzo kimoja cha kihistoria.'],
[97,2,'development',20,
 'Ongoza majadiliano ya vikundi kuhusu vyanzo vya Historia: vyanzo vya maandishi (vitabu, nyaraka), vyanzo vya mdomo (masimulizi, nyimbo), vyanzo vya akiolojia (mabaki, sanamu), na vyanzo vya picha.',
 'Jadili na uorodhesha vyanzo mbalimbali vya Historia na eleza mfano wa kila chanzo.',
 'Vyanzo mbalimbali vya Historia vimetambuliwa na kuelezwa kwa usahihi.'],
[97,4,'design',10,
 'Gawanya vyanzo mbalimbali kwa vikundi. Kila kikundi kiwasilishe chanzo chake na mfano wa jinsi kinavyotumika.',
 'Wasilisha chanzo kilichopewa kwa darasa, ukitoa mfano halisi wa chanzo hicho.',
 'Chanzo cha Historia kimebainishwa na kuelezwa vizuri kwa mfano sahihi.'],
[97,3,'realisation',5,
 'Kila mwanafunzi aorodheshe vyanzo vine vya Historia na atoe mfano mmoja kwa kila chanzo.',
 'Orodhesha vyanzo 4 vya Historia na toa mfano mmoja kwa kila chanzo.',
 'Vyanzo vine vya Historia vimeorodheshwa na mifano sahihi imetolewa.'],

// 98: Tathmini ubora na mapungufu ya vyanzo vya Historia
[98,7,'introduction',5,
 'Onyesha nakala mbili zinazoelezea tukio moja lakini zinatoa habari tofauti. Uliza: Ni ipi inayostahili kuaminiwa zaidi?',
 'Linganisha vyanzo viwili na pendekeza kipi ni cha kuaminika zaidi na kwa nini.',
 'Wanafunzi wanaonyesha uwezo wa kutathmini chanzo kidogo cha kihistoria.'],
[98,2,'development',20,
 'Ongoza majadiliano ya vikundi tathmini ubora (uhakika, uaminifu, uhalali) na mapungufu (upendeleo, kukosekana kwa sehemu, upotevu wa muda) ya vyanzo mbalimbali vya Historia.',
 'Jadili na utathmini ubora na mapungufu ya chanzo kilichopewa kwa kutumia vigezo vya uhalisi na uaminifu.',
 'Ubora na mapungufu ya vyanzo vya Historia vimetathminiwa kwa usahihi kwa kutumia vigezo sahihi.'],
[98,7,'design',10,
 'Kisa mafunzo: Vikundi vitathmini vyanzo viwili tofauti vya tukio moja la kihistoria na viorodheshe nguvu na udhaifu wa kila chanzo.',
 'Tathmini vyanzo viwili vya tukio moja la kihistoria na uandike nguvu na udhaifu wa kila kimoja.',
 'Tathmini yenye mantiki ya vyanzo vya kihistoria imeandikwa kwa kutumia vigezo sahihi.'],
[98,3,'realisation',5,
 'Kila mwanafunzi aeleze kwa sentensi mbili ubora mmoja na upungufu mmoja wa chanzo alichopewa.',
 'Andika ubora mmoja na upungufu mmoja wa chanzo cha Historia kilichopewa.',
 'Ubora na upungufu wa chanzo cha Historia vimebainishwa kwa usahihi.'],

// 99: Eleza umuhimu wa kusoma Historia kwa mtu binafsi na taifa
[99,5,'introduction',5,
 'Uliza: Kwa nini mashule yanafundisha Historia? Je, kujua Historia kunakusaidiaje wewe binafsi?',
 'Shiriki mawazo kuhusu umuhimu wa Historia kwa mtu binafsi.',
 'Wanafunzi wanatoa sababu za msingi za kusoma Historia.'],
[99,2,'development',20,
 'Ongoza majadiliano ya vikundi kuhusu umuhimu wa Historia: kutambua utambulisho, kujifunza makosa ya zamani, kuimarisha umoja wa taifa, kulinda urithi, kupanga mustakabali.',
 'Jadili na uandike umuhimu wa Historia kwa mtu binafsi na kwa taifa kwa ujumla.',
 'Umuhimu wa Historia kwa mtu binafsi na kwa taifa umeelezwa kwa kina na mifano sahihi.'],
[99,11,'design',10,
 'Mwalike mtaalamu (mwalimu mkongwe au mtaalam wa historia) ashirikiane na wanafunzi kueleza jinsi Historia inavyoathiri maisha yetu ya sasa.',
 'Sikiliza mtaalamu na uulize swali moja kuhusu umuhimu wa Historia kwa Tanzania ya sasa.',
 'Wanafunzi wanabainisha angalau njia tatu za Historia kuathiri maisha ya sasa.'],
[99,3,'realisation',5,
 'Kila mwanafunzi aorodheshe sababu tatu za umuhimu wa Historia — moja kwa binafsi, moja kwa jamii, moja kwa taifa.',
 'Orodhesha sababu tatu: moja kwa mtu binafsi, moja kwa jamii, moja kwa taifa.',
 'Sababu tatu sahihi za umuhimu wa Historia zimeorodheshwa.'],

// 100: Unganisha Historia na masomo mengine ya shuleni
[100,5,'introduction',5,
 'Uliza: Ni somo gani jingine shuleni linaloelezea matukio ya zamani? Historia inaunganika vipi na Jiografia, Kiswahili au Uraia?',
 'Pendekeza masomo mengine yanayounganika na Historia.',
 'Wanafunzi wanabainisha masomo mengine yanayohusiana na Historia.'],
[100,2,'development',20,
 'Ongoza vikundi kuchunguza uhusiano wa Historia na masomo mengine: Jiografia (maeneo ya matukio), Kiswahili (vyanzo vya mdomo), Uraia (sheria na serikali), Sayansi (teknolojia ya zamani).',
 'Jadili na uandike mfano mmoja wa jinsi Historia inavyounganika na masomo manne mengine.',
 'Uhusiano wa Historia na masomo mengine umebainishwa kwa mifano sahihi.'],
[100,4,'design',10,
 'Vikundi viunde ramani ya akili inayoonyesha Historia katikati na masomo mengine yanayounganika nayo.',
 'Unda ramani ya akili inayoonesha Historia ikiunganika na masomo mengine na eleza uhusiano huo.',
 'Ramani ya akili inayoonesha uhusiano wa Historia na masomo mengine imeundwa kwa usahihi.'],
[100,3,'realisation',5,
 'Kila mwanafunzi aeleze kwa mfano mmoja jinsi Historia inavyohusiana na somo jingine analonopenda.',
 'Eleza kwa sentensi mbili jinsi Historia inavyohusiana na somo jingine unalolipenda.',
 'Uhusiano wa Historia na somo jingine umebainishwa kwa mfano sahihi.'],

// ── Sura ya Pili: Binadamu wa Zamani na Mazingira Yake ───────────────────────

// 101: Eleza nadharia mbalimbali za mageuzi ya binadamu
[101,3,'introduction',5,
 'Onyesha picha za sokwe na binadamu. Uliza: Je, binadamu alitoka wapi? Kuna nadharia gani?',
 'Angalia picha na toa mawazo ya awali kuhusu asili ya binadamu.',
 'Wanafunzi wanaonyesha udadisi kuhusu asili ya binadamu.'],
[101,2,'development',20,
 'Ongoza majadiliano ya vikundi kuhusu nadharia za mageuzi ya binadamu: Nadharia ya Mageuzi ya Darwin, Nadharia ya Uumbaji, na nadharia nyingine. Toa matini za kusaidia.',
 'Jadili nadharia mbalimbali za mageuzi ya binadamu katika vikundi na wasilisha muhtasari.',
 'Nadharia mbalimbali za mageuzi ya binadamu zimeelezwa kwa usahihi.'],
[101,2,'design',10,
 'Vikundi vilinganishe nadharia: Zinaungana vipi? Zinatofautiana vipi? Ni ipi inayoungwa mkono na ushahidi wa kisayansi zaidi?',
 'Linganisha nadharia mbili za mageuzi na bainisha tofauti na mfanano wao.',
 'Nadharia za mageuzi zimlinganishwa kwa usahihi.'],
[101,3,'realisation',5,
 'Kila mwanafunzi aeleze kwa maneno yake nadharia moja ya mageuzi ya binadamu.',
 'Eleza kwa sentensi tatu nadharia moja ya mageuzi ya binadamu.',
 'Nadharia moja ya mageuzi ya binadamu imeelezwa kwa usahihi.'],

// 102: Eleza hatua za mageuzi ya binadamu
[102,1,'introduction',5,
 'Onyesha mstari wa muda (timeline) wa hatua za mageuzi ya binadamu. Uliza wanafunzi kuupanga.',
 'Angalia mstari wa muda na ujaribu kuupanga kwa mpangilio sahihi.',
 'Wanafunzi wanajaribu kupanga hatua za mageuzi kwa mpangilio.'],
[102,2,'development',20,
 'Ongoza majadiliano ya vikundi kuhusu hatua za mageuzi: Australopithecus, Homo habilis, Homo erectus, Homo sapiens. Eleza sifa za kila hatua na jinsi ilivyobadilika.',
 'Jadili hatua za mageuzi katika vikundi na uandike sifa za kila hatua kwenye jedwali.',
 'Hatua za mageuzi ya binadamu kutoka sokwe hadi binadamu wa kisasa zimeelezwa kwa usahihi.'],
[102,4,'design',10,
 'Vikundi viunde mstari wa muda unaoonyesha hatua za mageuzi ya binadamu na sifa za kila hatua.',
 'Unda mstari wa muda unaoonesha hatua za mageuzi ya binadamu na sifa za kila hatua.',
 'Mstari wa muda wenye hatua sahihi za mageuzi umeundwa.'],
[102,3,'realisation',5,
 'Kila mwanafunzi aorodheshe hatua nne za mageuzi ya binadamu kwa mpangilio sahihi na sifa moja ya kila hatua.',
 'Orodhesha hatua 4 za mageuzi kwa mpangilio na sifa moja ya kila hatua.',
 'Hatua nne za mageuzi zimeorodheshwa kwa mpangilio sahihi na sifa sahihi.'],

// 103: Eleza maisha ya binadamu katika Zama za Mawe za Kale
[103,3,'introduction',5,
 'Uliza: Watu wa zamani kabla ya kugunduliwa moto waliishi vipi? Walilaa nini? Waliishi wapi?',
 'Pendekeza jinsi watu wa zamani wanavyofikiriwa walivyoishi.',
 'Wanafunzi wanabainisha mambo mawili kuhusu maisha ya zamani.'],
[103,2,'development',20,
 'Ongoza majadiliano ya vikundi kuhusu maisha ya binadamu katika Zama za Mawe za Kale: uwindaji na ukusanyaji, maisha ya kuhamahama, kukaa mapangoni, matumizi ya zana za mawe.',
 'Jadili na uandike vipengele vya maisha ya binadamu katika Zama za Mawe za Kale.',
 'Maisha ya binadamu katika Zama za Mawe za Kale yameelezwa kwa usahihi.'],
[103,4,'design',10,
 'Vikundi viandike na kuchora picha inayoonyesha siku ya kawaida ya binadamu wa Zama za Mawe za Kale.',
 'Chora na ueleze picha inayoonesha maisha ya kawaida ya binadamu wa Zama za Mawe za Kale.',
 'Picha sahihi inayoonesha maisha ya Zama za Mawe imechorwa na kuelezwa.'],
[103,3,'realisation',5,
 'Kila mwanafunzi aeleze vipengele vitatu vya maisha ya binadamu katika Zama za Mawe za Kale.',
 'Eleza vipengele vitatu vya maisha ya binadamu katika Zama za Mawe za Kale.',
 'Vipengele vitatu sahihi vya maisha ya Zama za Mawe vimebainishwa.'],

// 104: Tofautisha Zama za Mawe za Kale, Kati na za Karibuni
[104,3,'introduction',5,
 'Onyesha mstari wa muda wa Zama za Mawe. Uliza: Zama hizi zinatofautiana vipi?',
 'Angalia mstari wa muda na jaribu kubainisha tofauti kati ya Zama za Mawe.',
 'Wanafunzi wanajaribu kutofautisha Zama za Mawe.'],
[104,2,'development',20,
 'Ongoza vikundi kulinganisha Zama za Mawe za Kale (uwindaji, mawe makubwa), Kati (zana ndogo-ndogo, mazingira mapya) na za Karibuni (kilimo cha mwanzo, mifugo).',
 'Jaza jedwali la ulinganisho la Zama za Mawe tatu kwa kutumia matini uliyopewa.',
 'Tofauti kati ya Zama za Mawe za Kale, Kati na za Karibuni zimebainishwa kwa usahihi.'],
[104,6,'design',10,
 'Fikiri-andika-jozisha-shirikisha: Kila mwanafunzi aandike tofauti mbili, ajozishe na mwenzake, wasilishane.',
 'Andika tofauti mbili kati ya Zama za Mawe, jozisha na mwenzako na shirikisha darasa.',
 'Tofauti sahihi kati ya Zama za Mawe zimebainishwa.'],
[104,3,'realisation',5,
 'Kila mwanafunzi aorodheshe tofauti mbili kati ya Zama za Mawe za Kale na za Karibuni.',
 'Orodhesha tofauti mbili kati ya Zama za Mawe za Kale na za Karibuni.',
 'Tofauti sahihi mbili kati ya Zama za Mawe zimebainishwa.'],

// 105: Eleza zana zilizotumiwa na binadamu wa zamani
[105,1,'introduction',5,
 'Onyesha picha za zana za mawe za zamani. Uliza: Zana hizi zilifanywa na nini? Zilitumika kwa nini?',
 'Angalia picha na toa mawazo kuhusu matumizi ya zana za mawe.',
 'Wanafunzi wanabainisha zana na matumizi yake ya awali.'],
[105,2,'development',20,
 'Ongoza majadiliano ya vikundi kuhusu zana za mawe (visu, nguruwe, mikuki) na zana za baadaye (shoka, sindano za mfupa). Eleza jinsi zilivyotengenezwa na kutumika.',
 'Jadili zana za kila Zama za Mawe, jinsi zilivyotengenezwa na matumizi yake. Andika muhtasari.',
 'Zana za binadamu wa zamani zimebainishwa na kuelezwa jinsi zilivyotengenezwa na kutumika.'],
[105,4,'design',10,
 'Vikundi vichoree na vibandike jina na matumizi ya zana tano za zamani kwenye karatasi kubwa.',
 'Chora zana tano za zamani, zipe majina na ueleze matumizi ya kila zana.',
 'Zana tano za binadamu wa zamani zimechorwa na kuelezwa matumizi yake kwa usahihi.'],
[105,3,'realisation',5,
 'Kila mwanafunzi aorodheshe zana tatu za binadamu wa zamani na matumizi ya kila zana.',
 'Orodhesha zana tatu za binadamu wa zamani na matumizi ya kila moja.',
 'Zana tatu za binadamu wa zamani zimeorodheshwa na matumizi yake yameelezwa.'],

// 106: Eleza maeneo yaliyogunduliwa mabaki ya binadamu wa zamani Tanzania
[106,1,'introduction',5,
 'Onyesha ramani ya Tanzania ukionyesha Bonde la Olduvai, Laetoli na maeneo mengine. Uliza: Kwa nini maeneo haya ni maarufu?',
 'Angalia ramani na taja maeneo unayoyajua ambayo ni maarufu kihistoria.',
 'Wanafunzi wanabainisha angalau eneo moja la kiakiolojia Tanzania.'],
[106,2,'development',20,
 'Ongoza majadiliano ya vikundi kuhusu maeneo ya kiakiolojia Tanzania: Bonde la Olduvai (Arusha), Laetoli (alama za miguu ya zamani), Kondoa Irangi (michoro ya mapangoni), Engaruka.',
 'Jadili maeneo ya kiakiolojia Tanzania, jinsi yalivyogunduliwa na umuhimu wake.',
 'Maeneo ya kiakiolojia Tanzania yamebainishwa na kuelezwa kwa usahihi.'],
[106,12,'design',10,
 'Vikundi vitafiti moja ya maeneo ya kiakiolojia Tanzania kwa kina na viwasilishe matokeo.',
 'Tafiti eneo moja la kiakiolojia Tanzania na uwasilishe ukweli muhimu watano kuhusu eneo hilo.',
 'Eneo la kiakiolojia Tanzania limetafitishwa na kuwasilishwa kwa usahihi.'],
[106,3,'realisation',5,
 'Kila mwanafunzi ataje maeneo matatu ya kiakiolojia Tanzania na mabaki yaliyopatikana kila eneo.',
 'Taja maeneo matatu ya kiakiolojia Tanzania na mabaki yaliyopatikana kila eneo.',
 'Maeneo matatu ya kiakiolojia Tanzania yametajwa na mabaki yake yamebainishwa.'],

// 107: Eleza umuhimu wa maeneo ya kiakiolojia kama Olduvai
[107,7,'introduction',5,
 'Simulia ugunduzi wa Louis Leakey huko Olduvai. Uliza: Kwa nini ugunduzi huu ni muhimu kwa historia ya binadamu?',
 'Sikiliza hadithi ya ugunduzi na eleza kwa nini unafikiria ni muhimu.',
 'Wanafunzi wanabainisha umuhimu wa ugunduzi wa Olduvai.'],
[107,2,'development',20,
 'Ongoza majadiliano ya vikundi kuhusu umuhimu wa maeneo ya kiakiolojia: kuthibitisha nadharia za mageuzi, kuelewa maisha ya zamani, kuvutia utalii, kulinda urithi wa Taifa.',
 'Jadili umuhimu wa maeneo ya kiakiolojia Tanzania na uandike hoja tano za umuhimu huu.',
 'Umuhimu wa maeneo ya kiakiolojia Tanzania umebainishwa kwa usahihi.'],
[107,2,'design',10,
 'Vikundi viunde hoja kwa nini Tanzania inapaswa kulinda na kutangaza maeneo yake ya kiakiolojia.',
 'Unda hoja tatu za kwa nini Tanzania inapaswa kulinda maeneo yake ya kiakiolojia.',
 'Hoja sahihi za kulinda maeneo ya kiakiolojia Tanzania zimeundwa.'],
[107,3,'realisation',5,
 'Kila mwanafunzi aeleze umuhimu wa Bonde la Olduvai kwa Tanzania na kwa historia ya binadamu.',
 'Eleza umuhimu wa Bonde la Olduvai katika sentensi mbili.',
 'Umuhimu wa Bonde la Olduvai umebainishwa kwa usahihi.'],

// ── Sura ya Tatu: Jamii za Mapema ────────────────────────────────────────────

// 108: Tambua makundi ya wawindaji, wafugaji na wakulima wa mapema
[108,5,'introduction',5,
 'Uliza: Watu wa zamani Africa Mashariki walijipatia chakula vipi? Waliishi vipi? Andika majibu ubaoni.',
 'Pendekeza njia wanazofikiria watu wa zamani walijipatia chakula.',
 'Wanafunzi wanabainisha njia za msingi za kujipatia chakula.'],
[108,2,'development',20,
 'Ongoza majadiliano ya vikundi kutambua makundi makuu ya watu wa mapema: wawindaji-wakusanyaji (hunters-gatherers), wafugaji (pastoralists), na wakulima wa mapema (early farmers). Eleza sifa za kila kundi.',
 'Jadili makundi ya watu wa mapema Afrika Mashariki na uziorodheshe sifa za kila kundi.',
 'Makundi ya wawindaji, wafugaji na wakulima wa mapema yamebainishwa kwa usahihi.'],
[108,6,'design',10,
 'Fikiri-andika-jozisha-shirikisha: Kila mwanafunzi achague kundi moja na aeleze sifa zake, kisha ajadili na mwenzake.',
 'Chagua kundi moja, andika sifa zake, jozisha na mwenzako na shirikisha darasa.',
 'Sifa za kundi lililochaguliwa zimebainishwa kwa usahihi.'],
[108,3,'realisation',5,
 'Kila mwanafunzi aorodheshe makundi matatu ya watu wa mapema na sifa moja ya kila kundi.',
 'Orodhesha makundi matatu na sifa moja ya kila kundi.',
 'Makundi matatu ya watu wa mapema yameorodheshwa na sifa sahihi zimebainishwa.'],

// 109: Eleza mfumo wa maisha wa kila kundi la watu wa mapema
[109,2,'introduction',5,
 'Gawanya darasa katika makundi matatu yanayowakilisha wawindaji, wafugaji na wakulima. Kila kundi likae pamoja na lijadili wanachojua kuhusu kundi lake.',
 'Jadili katika kundi lako unachojua kuhusu mfumo wa maisha ya kundi lako.',
 'Wanafunzi wanaonyesha maarifa ya awali kuhusu mfumo wa maisha ya kundi lao.'],
[109,2,'development',20,
 'Ongoza kila kundi kuchunguza kwa kina mfumo wa maisha ya kundi lake: chakula, makazi, zana, mfumo wa kijamii, mahusiano na mazingira. Vikundi viwasilishe kwa darasa zima.',
 'Chunguza mfumo wa maisha ya kundi lako na uwasilishe: chakula, makazi, zana na mfumo wa kijamii.',
 'Mfumo wa maisha wa kila kundi la watu wa mapema umebainishwa kwa usahihi.'],
[109,10,'design',10,
 'Kila kundi liigize siku ya kawaida ya kundi lake mbele ya darasa — wawindaji wakienda kuwinda, wafugaji wakihama na mifugo, wakulima wakifanya kazi shambani.',
 'Igiza siku ya kawaida ya kundi lako mbele ya darasa ukionyesha shughuli za kila siku.',
 'Mfumo wa maisha wa kundi umebainishwa kupitia mchezo wa kuigiza.'],
[109,3,'realisation',5,
 'Kila mwanafunzi aeleze tofauti mbili za mfumo wa maisha kati ya wawindaji na wakulima wa mapema.',
 'Eleza tofauti mbili za mfumo wa maisha kati ya wawindaji-wakusanyaji na wakulima wa mapema.',
 'Tofauti mbili sahihi za mfumo wa maisha kati ya makundi zimebainishwa.'],

// 110: Eleza sababu za uhamaji wa makabila Afrika Mashariki
[110,5,'introduction',5,
 'Uliza: Kwa nini watu wanaacha makwao na kwenda sehemu nyingine? Nini kinaweza kusababisha uhamaji?',
 'Toa sababu wanazofikiria zinaweza kusababisha watu kuhamia mahali pengine.',
 'Wanafunzi wanabainisha sababu mbili za msingi za uhamaji.'],
[110,2,'development',20,
 'Ongoza majadiliano ya vikundi kuhusu sababu za uhamaji wa makabila Afrika Mashariki: ukame, ukosefu wa ardhi, vita, magonjwa, kutafuta malisho, biashara.',
 'Jadili na uorodheshe sababu za uhamaji wa makabila, ukizingatia mazingira ya Afrika Mashariki.',
 'Sababu za uhamaji wa makabila Afrika Mashariki zimebainishwa kwa usahihi.'],
[110,1,'design',10,
 'Onyesha ramani ya Afrika Mashariki ukionyesha njia za uhamaji wa makabila makubwa. Vikundi vibainishe sababu za kila uhamaji ulioonyeshwa.',
 'Angalia ramani ya uhamaji wa makabila na bainisha sababu za uhamaji ulioonyeshwa.',
 'Sababu za uhamaji wa makabila kwenye ramani zimebainishwa kwa usahihi.'],
[110,3,'realisation',5,
 'Kila mwanafunzi aorodheshe sababu nne za uhamaji wa makabila Afrika Mashariki.',
 'Orodhesha sababu nne za uhamaji wa makabila Afrika Mashariki.',
 'Sababu nne sahihi za uhamaji wa makabila zimeorodheshwa.'],

// 111: Eleza athari za uhamaji kwa makabila
[111,7,'introduction',5,
 'Uliza: Unafikiri uhamaji wa makabila uliathiri vipi watu waliohama na wale waliokutana nao?',
 'Pendekeza athari chanya na hasi za uhamaji wa makabila.',
 'Wanafunzi wanabainisha athari moja chanya na moja hasi ya uhamaji.'],
[111,2,'development',20,
 'Ongoza vikundi kuchunguza athari za uhamaji: athari chanya (biashara, kubadilishana utamaduni, teknolojia mpya, makazi mapya) na athari hasi (migogoro ya ardhi, vita, magonjwa).',
 'Jadili na uorodheshe athari chanya na hasi za uhamaji wa makabila kwa Tanzania.',
 'Athari za uhamaji kwa makabila yaliyohamia na yaliyokaribishwa zimebainishwa kwa usahihi.'],
[111,2,'design',10,
 'Vikundi viunde jedwali linalolinganisha athari chanya na hasi za uhamaji wa makabila Afrika Mashariki.',
 'Unda jedwali la athari chanya na hasi za uhamaji wa makabila.',
 'Jedwali sahihi la athari za uhamaji limeundwa.'],
[111,3,'realisation',5,
 'Kila mwanafunzi aeleze athari mbili za uhamaji — moja chanya na moja hasi.',
 'Eleza athari mbili za uhamaji wa makabila — moja chanya na moja hasi.',
 'Athari mbili sahihi za uhamaji — chanya na hasi — zimebainishwa.'],

// 112: Eleza mwingiliano wa makabila
[112,5,'introduction',5,
 'Uliza: Makabila yalipokutana, yalishirikiana vipi? Ni nini kinachofanya makabila yaishi pamoja kwa amani?',
 'Pendekeza njia ambazo makabila yangeweza kushirikiana.',
 'Wanafunzi wanabainisha njia moja ya mwingiliano wa makabila.'],
[112,2,'development',20,
 'Ongoza majadiliano ya vikundi kuhusu njia za mwingiliano wa makabila: biashara ya kubadilishana, ndoa za mchanganyiko, ushirikiano wa kilimo, kubadilishana lugha na utamaduni.',
 'Jadili na uorodheshe njia za mwingiliano wa makabila kibiashara, kijamii na kiutamaduni.',
 'Njia za mwingiliano wa makabila zimebainishwa kwa usahihi.'],
[112,2,'design',10,
 'Vikundi viunde picha ya makabila mawili yanayoshirikiana — vikiorodhesha kila aina ya mwingiliano.',
 'Unda picha au mchoro unaoonyesha njia za mwingiliano wa makabila mawili.',
 'Njia za mwingiliano wa makabila zinaonyeshwa kwa usahihi katika kazi ya kikundi.'],
[112,3,'realisation',5,
 'Kila mwanafunzi aeleze njia tatu za mwingiliano wa makabila na mfano mmoja wa kila njia.',
 'Eleza njia tatu za mwingiliano wa makabila na toa mfano mmoja kwa kila njia.',
 'Njia tatu za mwingiliano wa makabila zimebainishwa na mifano sahihi imetolewa.'],

// 113: Tathmini athari za mwingiliano kwa maendeleo ya Tanzania
[113,7,'introduction',5,
 'Uliza: Je, makabila kuishi pamoja na kushirikiana kulifaidisha Tanzania? Ilitoa changamoto gani?',
 'Pendekeza faida na changamoto za makabila kuishi pamoja.',
 'Wanafunzi wanabainisha faida na changamoto moja ya mwingiliano wa makabila.'],
[113,2,'development',20,
 'Ongoza majadiliano tathmini ya athari za mwingiliano wa makabila kwa maendeleo ya Tanzania: kubadilishana maarifa ya kilimo, teknolojia, lugha (Kiswahili), biashara, na migogoro ya ardhi.',
 'Jadili na utathmini athari za mwingiliano wa makabila kwa maendeleo ya Tanzania.',
 'Athari za mwingiliano wa makabila kwa maendeleo ya Tanzania zimetathminiwa kwa hoja sahihi.'],
[113,2,'design',10,
 'Vikundi viunde hoja: Je, mwingiliano wa makabila ulisaidia au kudhuru maendeleo ya Tanzania zaidi?',
 'Unda hoja tatu zinazosaidia au kupinga kuwa mwingiliano wa makabila ulichangia maendeleo ya Tanzania.',
 'Hoja zenye mantiki kuhusu athari za mwingiliano wa makabila zimeundwa.'],
[113,3,'realisation',5,
 'Kila mwanafunzi aeleze athari mbili za mwingiliano wa makabila kwa maendeleo ya Tanzania.',
 'Eleza athari mbili za mwingiliano wa makabila kwa maendeleo ya Tanzania.',
 'Athari mbili za mwingiliano wa makabila kwa Tanzania zimebainishwa kwa usahihi.'],

// ── Sura ya Nne: Uhusiano wa Kitanzania na Dunia ─────────────────────────────

// 114: Eleza asili na historia ya uhusiano wa Watanzania na mataifa mengine
[114,5,'introduction',5,
 'Uliza: Je, Tanzania iliwahi kuwa na uhusiano na nchi nyingine kabla ya ukoloni? Nchi zipi?',
 'Taja nchi au mataifa ambayo Watanzania wanaweza kuwa walikuwa na uhusiano nazo.',
 'Wanafunzi wanabainisha mataifa mengi yaliyoweza kuwa na uhusiano na Tanzania.'],
[114,2,'development',20,
 'Ongoza majadiliano ya vikundi kuhusu asili ya uhusiano wa Tanzania na mataifa mengine: biashara ya pwani na Uarabuni, India, China; uhusiano na makabila ya jirani.',
 'Jadili asili na historia ya uhusiano wa Watanzania na mataifa mengine na uandike muhtasari.',
 'Asili na historia ya uhusiano wa Watanzania na mataifa mengine imebainishwa kwa usahihi.'],
[114,1,'design',10,
 'Onyesha ramani ya biashara ya Bahari ya Hindi ukionyesha njia za biashara. Vikundi vibainishe mataifa yaliyoshiriki.',
 'Angalia ramani ya njia za biashara na ubainishe mataifa yaliyoshirikiana na Tanzania kibiashara.',
 'Mataifa yaliyoshirikiana na Tanzania kibiashara yamebainishwa kwenye ramani.'],
[114,3,'realisation',5,
 'Kila mwanafunzi abainishe njia tatu za uhusiano wa Tanzania na mataifa mengine.',
 'Bainisha njia tatu ambazo Tanzania iliungana na mataifa mengine kabla ya ukoloni.',
 'Njia tatu sahihi za uhusiano wa Tanzania na mataifa mengine zimebainishwa.'],

// 115: Bainisha njia mbalimbali za uhusiano (biashara, ndoa, vita)
[115,2,'introduction',5,
 'Uliza: Biashara, ndoa na vita — jinsi gani hizi zote ni aina za uhusiano kati ya watu au mataifa?',
 'Eleza jinsi biashara, ndoa na vita vinavyoweza kuunganisha au kugawanya watu.',
 'Wanafunzi wanabainisha njia tatu za msingi za uhusiano.'],
[115,2,'development',20,
 'Ongoza majadiliano ya vikundi kubainisha na kueleza njia za uhusiano: biashara (mali na bidhaa), ndoa za mchanganyiko (uhusiano wa kimwili na kijamii), vita na mapatano ya amani.',
 'Jadili na ubainishe mifano ya kila njia ya uhusiano kutoka historia ya Tanzania.',
 'Njia mbalimbali za uhusiano wa Kitanzania na mataifa mengine zimebainishwa kwa mifano.'],
[115,10,'design',10,
 'Mchezo wa kuigiza: Kikundi kimoja kiigize mazungumzo ya biashara kati ya mfanyabiashara wa Tanzania na wa Uarabuni wa karne ya kumi na mbili.',
 'Igiza mazungumzo ya biashara ya zamani kati ya Tanzania na mataifa mengine.',
 'Uhusiano wa kibiashara unaigizwa kwa usahihi ukionyesha aina za bidhaa na namna ya kufanya biashara.'],
[115,3,'realisation',5,
 'Kila mwanafunzi aorodheshe njia tatu za uhusiano wa Tanzania na mataifa na atoe mfano mmoja wa kila njia.',
 'Orodhesha njia tatu na toa mfano mmoja wa kila njia ya uhusiano.',
 'Njia tatu na mifano sahihi ya uhusiano wa Tanzania na mataifa imebainishwa.'],

// 116-122: Uhusiano na Ulaya/Waarabu/athari
[116,3,'introduction',5,
 'Uliza: Wazungu walikuja Tanzania wakati gani wa kwanza? Waliingiaje nchini?',
 'Toa mawazo yao kuhusu ujio wa kwanza wa Wazungu Tanzania.',
 'Wanafunzi wanabainisha kipindi cha awali cha Wazungu Tanzania.'],
[116,2,'development',20,
 'Ongoza majadiliano ya vikundi kuhusu uhusiano wa awali wa Watanzania na Wazungu: biashara ya pwani, utafiti wa kijiografia, misheni ya kidini, kabla ya ukoloni rasmi.',
 'Jadili uhusiano wa awali wa Watanzania na Wazungu na andika muhtasari.',
 'Uhusiano wa awali wa Watanzania na Wazungu kabla ya ukoloni umebainishwa kwa usahihi.'],
[116,1,'design',10,
 'Onyesha ramani ya njia za wasafiri wa Ulaya Afrika Mashariki. Vikundi vibainishe maeneo waliyofika.',
 'Angalia ramani na ubainishe maeneo ya Tanzania yaliyofikiwa na wasafiri wa Ulaya.',
 'Njia za wasafiri wa Ulaya Afrika Mashariki zimebainishwa kwa usahihi.'],
[116,3,'realisation',5,
 'Eleza kwa sentensi mbili asili ya uhusiano wa kwanza wa Watanzania na Wazungu.',
 'Andika sentensi mbili kuhusu asili ya uhusiano wa kwanza wa Watanzania na Wazungu.',
 'Uhusiano wa awali wa Watanzania na Wazungu umebainishwa kwa usahihi.'],

[117,2,'introduction',5,
 'Uliza: Uhusiano na Wazungu ulifaidisha Tanzania? Ulidhuru Tanzania? Jinsi gani?',
 'Pendekeza faida na hasara za uhusiano wa Watanzania na Wazungu.',
 'Wanafunzi wanabainisha faida na hasara moja ya uhusiano.'],
[117,2,'development',20,
 'Ongoza majadiliano tathmini ya athari za kiuchumi (biashara, rasilimali) na kijamii (dini, elimu) za uhusiano na Wazungu.',
 'Jadili na utathmini athari za kiuchumi na kijamii za uhusiano wa Watanzania na Wazungu.',
 'Athari za kiuchumi na kijamii za uhusiano na Wazungu zimetathminiwa kwa usahihi.'],
[117,2,'design',10,
 'Vikundi viunde jedwali la athari chanya na hasi za uhusiano na Wazungu kiuchumi na kijamii.',
 'Unda jedwali la athari chanya na hasi za uhusiano na Wazungu.',
 'Jedwali sahihi la athari za uhusiano na Wazungu limeundwa.'],
[117,3,'realisation',5,
 'Eleza athari mbili za kiuchumi na athari mbili za kijamii za uhusiano na Wazungu.',
 'Eleza athari mbili za kiuchumi na mbili za kijamii za uhusiano wa Tanzania na Wazungu.',
 'Athari za kiuchumi na kijamii za uhusiano na Wazungu zimebainishwa kwa usahihi.'],

[118,5,'introduction',5,
 'Uliza: Waarabu waliingia Tanzania lini? Walitoka wapi? Walikuwa wanafanya nini?',
 'Toa mawazo ya awali kuhusu ujio wa Waarabu Tanzania.',
 'Wanafunzi wanabainisha maarifa yao ya awali kuhusu Waarabu Tanzania.'],
[118,2,'development',20,
 'Ongoza majadiliano ya vikundi kuhusu biashara ya pwani ya Waarabu: bidhaa za biashara (ivory, dhahabu, nguo, viungo), miji ya pwani (Kilwa, Mombasa, Zanzibar), na mfumo wa biashara.',
 'Jadili biashara ya pwani ya Waarabu na Tanzania na uandike bidhaa zilizobinafsishwa na miji iliyohusika.',
 'Uhusiano wa biashara kati ya Tanzania na Waarabu umebainishwa kwa usahihi.'],
[118,1,'design',10,
 'Onyesha ramani ya njia za biashara za Waarabu pwani ya Afrika Mashariki. Vikundi vibainishe bandari na mji zilizohusika.',
 'Angalia ramani na ubainishe bandari na miji ya biashara ya Waarabu pwani ya Tanzania.',
 'Njia za biashara za Waarabu pwani ya Afrika Mashariki zimebainishwa kwa usahihi.'],
[118,3,'realisation',5,
 'Eleza kwa sentensi mbili bidhaa kuu mbili zilizobinafsishwa na Waarabu Tanzania.',
 'Eleza bidhaa kuu mbili zilizobinafsishwa na Waarabu Tanzania.',
 'Bidhaa kuu za biashara ya Waarabu Tanzania zimebainishwa kwa usahihi.'],

[119,7,'introduction',5,
 'Onyesha picha au elezea biashara ya watumwa. Uliza: Biashara hii iliathiri vipi Watanzania?',
 'Eleza hisia zao kuhusu biashara ya watumwa na athari zake.',
 'Wanafunzi wanaonyesha ufahamu wa msingi wa athari za biashara ya watumwa.'],
[119,2,'development',20,
 'Ongoza majadiliano ya vikundi kuhusu athari za biashara ya watumwa na ya ivory: idadi ya watu ilipungua, familia zilifarakana, mifumo ya kijamii ilibomolewa, uchumi uliathirika.',
 'Jadili athari za biashara ya watumwa na bidhaa nyingine kwa Tanzania.',
 'Athari za biashara ya watumwa na bidhaa kwa Tanzania zimebainishwa kwa usahihi.'],
[119,2,'design',10,
 'Vikundi viunde hoja mbili kwa na mbili dhidi ya: "Biashara ya Waarabu ilinufaisha Tanzania zaidi kuliko kuidhuru".',
 'Unda hoja kwa na dhidi ya biashara ya Waarabu Tanzania.',
 'Hoja zenye mantiki kwa na dhidi ya biashara ya Waarabu Tanzania zimeundwa.'],
[119,3,'realisation',5,
 'Eleza athari mbili za biashara ya watumwa kwa Tanzania.',
 'Eleza athari mbili za biashara ya watumwa kwa jamii za Kitanzania.',
 'Athari mbili sahihi za biashara ya watumwa zimebainishwa.'],

[120,5,'introduction',5,
 'Uliza: Watu wengi wa Tanzania wanaomba Mungu leo. Hii ilianza lini? Kutoka wapi?',
 'Toa mawazo yao kuhusu asili ya dini Tanzania.',
 'Wanafunzi wanabainisha asili ya dini kuu Tanzania.'],
[120,2,'development',20,
 'Ongoza majadiliano kuhusu athari za kidini za uhusiano na Waarabu (uenezi wa Uislamu, misikiti, madrasas) na athari za kiutamaduni (lugha — Kiswahili ilikopwa maneno ya Kiarabu, mavazi, sanaa).',
 'Jadili athari za kidini na kiutamaduni za uhusiano na Waarabu kwa Tanzania.',
 'Athari za kidini na kiutamaduni za uhusiano na Waarabu zimebainishwa kwa usahihi.'],
[120,2,'design',10,
 'Vikundi vibainishe maneno ya Kiarabu yanayotumiwa katika Kiswahili na bidhaa za utamaduni wa Kiarabu zinazoonekana Tanzania.',
 'Orodhesha maneno 5 ya Kiarabu katika Kiswahili na bidhaa 3 za utamaduni wa Kiarabu Tanzania.',
 'Maneno ya Kiarabu katika Kiswahili na athari za utamaduni wa Kiarabu zimebainishwa.'],
[120,3,'realisation',5,
 'Eleza athari mbili za kidini na athari mbili za kiutamaduni za uhusiano na Waarabu.',
 'Eleza athari mbili za kidini na mbili za kiutamaduni za uhusiano na Waarabu Tanzania.',
 'Athari za kidini na kiutamaduni za uhusiano na Waarabu zimebainishwa.'],

[121,2,'introduction',5,
 'Uliza: Uhusiano wa Tanzania na mataifa mengine kabla ya ukoloni ulifaidisha Tanzania kwa njia gani?',
 'Toa faida wanazofikiria zilizotokana na uhusiano wa Tanzania na mataifa.',
 'Wanafunzi wanabainisha faida moja ya uhusiano wa nje.'],
[121,2,'development',20,
 'Ongoza majadiliano kuhusu athari chanya: biashara iliongeza utajiri, uenezi wa teknolojia mpya, maendeleo ya miji ya pwani, kubadilishana utamaduni na lugha, uenezi wa elimu.',
 'Jadili na uorodheshe athari chanya za uhusiano wa Tanzania na mataifa kabla ya ukoloni.',
 'Athari chanya za uhusiano wa Tanzania na mataifa mengine zimebainishwa kwa usahihi.'],
[121,2,'design',10,
 'Vikundi viunde mchoro unaoonyesha jinsi biashara na uhusiano na mataifa mengine ulifaidisha Tanzania.',
 'Unda mchoro unaoonesha athari chanya za uhusiano wa Tanzania na mataifa mengine.',
 'Mchoro sahihi wa athari chanya za uhusiano wa Tanzania na nje umeundwa.'],
[121,3,'realisation',5,
 'Orodhesha athari chanya tatu za uhusiano wa Tanzania na mataifa mengine.',
 'Orodhesha athari chanya tatu za uhusiano wa Tanzania na mataifa mengine kabla ya ukoloni.',
 'Athari chanya tatu sahihi za uhusiano wa Tanzania na nje zimeorodheshwa.'],

[122,7,'introduction',5,
 'Uliza: Uhusiano na mataifa mengine pia ulileta matatizo kwa Tanzania. Matatizo gani?',
 'Toa matatizo wanayofikiria yalitokana na uhusiano na mataifa mengine.',
 'Wanafunzi wanabainisha tatizo moja la uhusiano na mataifa mengine.'],
[122,2,'development',20,
 'Ongoza majadiliano kuhusu athari hasi: biashara ya watumwa (kupoteza watu), unyonyaji wa rasilimali, kupotea kwa uhuru, utegemezi wa kiuchumi, vita vilivyosababishwa na ushindani wa biashara.',
 'Jadili na uorodheshe athari hasi za uhusiano wa Tanzania na mataifa mengine kabla ya ukoloni.',
 'Athari hasi za uhusiano wa Tanzania na mataifa mengine zimebainishwa kwa usahihi.'],
[122,2,'design',10,
 'Vikundi vitathmini: Athari chanya au hasi za uhusiano na mataifa mengine zilikuwa kubwa zaidi kwa Tanzania?',
 'Jadili na uamue kwa hoja kama athari chanya au hasi zilikuwa kubwa zaidi.',
 'Tathmini yenye hoja za uhusiano wa Tanzania na mataifa mengine imewasilishwa.'],
[122,3,'realisation',5,
 'Eleza athari hasi mbili za uhusiano wa Tanzania na mataifa mengine kabla ya ukoloni.',
 'Eleza athari hasi mbili za uhusiano wa Tanzania na mataifa kabla ya ukoloni.',
 'Athari hasi mbili sahihi za uhusiano wa Tanzania na mataifa zimebainishwa.'],

// ── Sura ya Tano: Ujio wa Wakoloni na Upinzani ───────────────────────────────

[123,5,'introduction',5,
 'Uliza: Kwa nini Wazungu walikuja Afrika kwa wingi katika karne ya 19? Ni nini kiliwavutia?',
 'Toa mawazo yao kuhusu sababu za Wazungu kuja Afrika.',
 'Wanafunzi wanabainisha angalau sababu moja ya kiuchumi ya Wazungu kuja Afrika.'],
[123,2,'development',20,
 'Ongoza majadiliano ya vikundi kuhusu sababu za kiuchumi za ujio wa ukoloni: kutafuta masoko mapya, rasilimali ghafi, ardhi kwa ukulima na biashara, mapinduzi ya viwanda yaliyohitaji malighafi.',
 'Jadili na uorodheshe sababu za kiuchumi zilizopelekea Wazungu kuja Afrika.',
 'Sababu za kiuchumi za ujio wa Wazungu Afrika zimebainishwa kwa usahihi.'],
[123,1,'design',10,
 'Onyesha ramani ya Afrika ikionyesha mgawanyo wa Ulaya (Mkutano wa Berlin 1884-85). Vikundi vitathmini sababu za kiuchumi za mgawanyo huo.',
 'Angalia ramani ya mgawanyo wa Afrika na ubainishe sababu za kiuchumi za mgawanyo huo.',
 'Sababu za kiuchumi za mgawanyo wa Afrika zimebainishwa kwa usahihi kutoka kwa ramani.'],
[123,3,'realisation',5,
 'Orodhesha sababu tatu za kiuchumi zilizopelekea Wazungu kuja Afrika.',
 'Orodhesha sababu tatu za kiuchumi za Wazungu kuja Afrika.',
 'Sababu tatu sahihi za kiuchumi za ujio wa Wazungu Afrika zimeorodheshwa.'],

[124,2,'introduction',5,
 'Uliza: Sababu za kisiasa, kidini na kijamii pia ziliwasukuma Wazungu Afrika. Ni zipi?',
 'Pendekeza sababu za kisiasa, kidini na kijamii za ujio wa Wazungu Afrika.',
 'Wanafunzi wanabainisha sababu moja isiyo ya kiuchumi.'],
[124,2,'development',20,
 'Ongoza majadiliano ya vikundi kuhusu sababu za kisiasa (kushindana kwa nguvu za Ulaya), kidini (kueneza Ukristo) na kijamii (kuhamasika kwa utamaduni wa Ulaya, kubeba "mzigo wa mzungu").',
 'Jadili na uorodheshe sababu za kisiasa, kidini na kijamii za ujio wa wakoloni Afrika.',
 'Sababu za kisiasa, kidini na kijamii za ujio wa wakoloni zimebainishwa kwa usahihi.'],
[124,2,'design',10,
 'Vikundi viainishe sababu za ujio wa wakoloni katika makundi matatu: kiuchumi, kisiasa, na kijamii/kidini.',
 'Ainisha sababu za ujio wa wakoloni katika makundi ya kiuchumi, kisiasa, na kijamii/kidini.',
 'Sababu za ujio wa wakoloni zimeainishwa kwa usahihi katika makundi sahihi.'],
[124,3,'realisation',5,
 'Eleza sababu mbili zisizo za kiuchumi za Wazungu kuja Afrika.',
 'Eleza sababu mbili zisizo za kiuchumi zilizopelekea Wazungu kuja Afrika.',
 'Sababu mbili sahihi zisizo za kiuchumi za ujio wa wakoloni zimebainishwa.'],

[125,2,'introduction',5,
 'Uliza: Watu wa Tanzania walikaa kimya tu wakati Wazungu walikuja? Au walipigana dhidi yao?',
 'Toa mawazo kuhusu jinsi Watanzania wangeweza kupinga ukoloni.',
 'Wanafunzi wanabainisha njia moja ya upinzani dhidi ya ukoloni.'],
[125,2,'development',20,
 'Ongoza majadiliano ya vikundi kuhusu njia za upinzani: silaha (vita vya Majimaji, vita vya Hehe), diplomasia (mazungumzo, mapatano), upinzani wa amani (wagomaji, vikundi vya kisiasa).',
 'Jadili na uorodheshe njia mbalimbali za upinzani dhidi ya wakoloni Tanzania.',
 'Njia mbalimbali za upinzani dhidi ya wakoloni zimebainishwa kwa usahihi.'],
[125,2,'design',10,
 'Vikundi vilinganishe mbinu za upinzani kwa silaha na kwa diplomasia — ipi ilikuwa na mafanikio zaidi?',
 'Linganisha upinzani wa silaha na wa kidiplomasia — ipi ilifanikiwa zaidi na kwa nini?',
 'Njia za upinzani zimlinganishwa kwa hoja sahihi.'],
[125,3,'realisation',5,
 'Eleza njia tatu za upinzani dhidi ya ukoloni Tanzania.',
 'Eleza njia tatu za upinzani wa Watanzania dhidi ya ukoloni.',
 'Njia tatu sahihi za upinzani dhidi ya ukoloni zimebainishwa.'],

[126,7,'introduction',5,
 'Uliza: Upinzani dhidi ya ukoloni Tanzania ulifanikiwa? Ulikuwa na mapungufu gani?',
 'Toa mawazo yao kuhusu mafanikio na mapungufu ya upinzani dhidi ya ukoloni.',
 'Wanafunzi wanaeleza mafanikio moja na upungufu mmoja wa upinzani.'],
[126,2,'development',20,
 'Ongoza majadiliano tathmini ya mafanikio (kujenga umoja wa kitaifa, kuonyesha nguvu, kuchangia uhuru wa baadaye) na mapungufu (kutofanya kazi pamoja, silaha duni, kushindwa kijeshi).',
 'Jadili na utathmini mafanikio na mapungufu ya upinzani wa Watanzania dhidi ya ukoloni.',
 'Mafanikio na mapungufu ya upinzani dhidi ya ukoloni vimetathminiwa kwa usahihi.'],
[126,2,'design',10,
 'Vikundi viundee hoja mbili kwa upande: "Upinzani dhidi ya ukoloni Tanzania ulifanikiwa" na mbili dhidi yake.',
 'Unda hoja kwa upande na dhidi ya mafanikio ya upinzani dhidi ya ukoloni Tanzania.',
 'Hoja zenye mantiki kuhusu mafanikio ya upinzani zimeundwa.'],
[126,3,'realisation',5,
 'Eleza mafanikio mawili na mapungufu mawili ya upinzani dhidi ya ukoloni Tanzania.',
 'Eleza mafanikio mawili na mapungufu mawili ya upinzani dhidi ya ukoloni Tanzania.',
 'Mafanikio mawili na mapungufu mawili ya upinzani yamebainishwa kwa usahihi.'],

[127,7,'introduction',5,
 'Uliza: Mnasikia nini kuhusu Vita vya Majimaji? Vilianza lini? Vilisababishwa na nini?',
 'Toa maarifa yao ya awali kuhusu Vita vya Majimaji.',
 'Wanafunzi wanaonyesha maarifa yao ya awali kuhusu Vita vya Majimaji.'],
[127,2,'development',20,
 'Ongoza majadiliano ya vikundi kuhusu Vita vya Majimaji 1905-1907: sababu (kulazimishwa kufanya kazi, ushuru wa bidhaa, imani ya maji ya kinga), mwenendo wa vita, matokeo (kushindwa kwa Wajerumani kidogo, kupotea kwa watu wengi, ukame).',
 'Jadili sababu, mwenendo na matokeo ya Vita vya Majimaji na uandike muhtasari.',
 'Sababu, mwenendo na matokeo ya Vita vya Majimaji yamebainishwa kwa usahihi.'],
[127,1,'design',10,
 'Onyesha ramani ya Tanzania ukionyesha maeneo ya Vita vya Majimaji. Vikundi vibainishe maeneo na matukio makuu.',
 'Angalia ramani na ubainishe maeneo ya Tanzania yaliyohusika na Vita vya Majimaji.',
 'Maeneo ya Vita vya Majimaji yamebainishwa kwa usahihi kwenye ramani.'],
[127,3,'realisation',5,
 'Eleza sababu mbili na matokeo mawili ya Vita vya Majimaji.',
 'Eleza sababu mbili na matokeo mawili ya Vita vya Majimaji 1905-1907.',
 'Sababu mbili na matokeo mawili ya Vita vya Majimaji yamebainishwa kwa usahihi.'],

[128,2,'introduction',5,
 'Uliza: Vita vya Majimaji viliishia kushindwa. Bado vina umuhimu gani katika historia ya Tanzania?',
 'Pendekeza kwa nini Vita vya Majimaji vinazingatiwa muhimu licha ya kushindwa.',
 'Wanafunzi wanabainisha umuhimu wa awali wa Vita vya Majimaji.'],
[128,2,'development',20,
 'Ongoza majadiliano kuhusu umuhimu wa Vita vya Majimaji: mfano wa umoja wa kikabila, kichocheo cha harakati za uhuru, kuonyesha ujasiri wa Watanzania, somo la historia kwa vizazi.',
 'Jadili na uorodheshe umuhimu wa Vita vya Majimaji katika historia ya Tanzania.',
 'Umuhimu wa Vita vya Majimaji katika historia ya Tanzania umebainishwa kwa usahihi.'],
[128,2,'design',10,
 'Vikundi viandike hotuba fupi kutoka mtazamo wa kiongozi wa Vita vya Majimaji, wakieleza kwa nini wanajitoa kupigana.',
 'Andika hotuba fupi kutoka mtazamo wa kiongozi wa Vita vya Majimaji.',
 'Hotuba inayoonyesha ufahamu wa umuhimu wa Vita vya Majimaji imeandikwa.'],
[128,3,'realisation',5,
 'Eleza umuhimu wa Vita vya Majimaji katika historia ya Tanzania kwa sentensi tatu.',
 'Eleza umuhimu wa Vita vya Majimaji katika sentensi tatu.',
 'Umuhimu wa Vita vya Majimaji umebainishwa kwa usahihi.'],

// ── Sura ya Sita: Tanzania Chini ya Utawala wa Kikoloni ─────────────────────

[129,5,'introduction',5,
 'Uliza: Wajerumani walianzishaje utawala Tanzania? Je, walikuwa rafiki au wakali?',
 'Toa mawazo ya awali kuhusu jinsi Wajerumani walianzisha utawala Tanzania.',
 'Wanafunzi wanabainisha maarifa yao ya awali kuhusu utawala wa Kijerumani.'],
[129,2,'development',20,
 'Ongoza majadiliano ya vikundi kuhusu jinsi Wajerumani walianzisha utawala Tanzania: kutumia nguvu, mfumo wa Akida na Jumbe, sera za ushuru, kulazimisha kazi.',
 'Jadili jinsi Wajerumani walianzisha na kusimamia utawala Tanzania na uandike muhtasari.',
 'Jinsi Wajerumani walivyoanzisha utawala Tanzania imebainishwa kwa usahihi.'],
[129,1,'design',10,
 'Onyesha picha za vituo vya Kijerumani Tanzania na mfumo wa utawala. Vikundi vibainishe sifa za utawala wa Kijerumani.',
 'Angalia picha za vituo vya Kijerumani na ubainishe sifa za utawala wao Tanzania.',
 'Sifa za utawala wa Kijerumani Tanzania zimebainishwa kwa usahihi.'],
[129,3,'realisation',5,
 'Eleza jinsi Wajerumani walivyoanzisha utawala Tanzania kwa hatua tatu.',
 'Eleza jinsi Wajerumani walianzisha utawala Tanzania kwa hatua tatu.',
 'Jinsi Wajerumani walianzisha utawala Tanzania imebainishwa kwa hatua sahihi.'],

[130,2,'introduction',5,
 'Uliza: Ukoloni wa Kijerumani uliathiri vipi uchumi na jamii ya Tanzania?',
 'Pendekeza mabadiliko ya kiuchumi na kijamii yaliyotokea chini ya Wajerumani.',
 'Wanafunzi wanabainisha mabadiliko mawili ya kiuchumi au kijamii.'],
[130,2,'development',20,
 'Ongoza majadiliano kuhusu mabadiliko ya kiuchumi (kilimo cha biashara — kahawa, pamba, sisal; reli, miundombinu) na kijamii (mfumo wa elimu, dini, utawala wa matendo).',
 'Jadili mabadiliko ya kiuchumi na kijamii chini ya utawala wa Kijerumani Tanzania.',
 'Mabadiliko ya kiuchumi na kijamii chini ya Wajerumani yamebainishwa kwa usahihi.'],
[130,2,'design',10,
 'Vikundi viunde jedwali la mabadiliko ya kiuchumi na kijamii chini ya Wajerumani — chanya na hasi.',
 'Unda jedwali la mabadiliko ya kiuchumi na kijamii chini ya Wajerumani — chanya na hasi.',
 'Jedwali sahihi la mabadiliko chini ya Wajerumani limeundwa.'],
[130,3,'realisation',5,
 'Eleza mabadiliko mawili ya kiuchumi na mawili ya kijamii yaliyotokea chini ya Wajerumani Tanzania.',
 'Eleza mabadiliko mawili ya kiuchumi na mawili ya kijamii chini ya utawala wa Kijerumani.',
 'Mabadiliko manne sahihi chini ya Wajerumani yamebainishwa.'],

[131,3,'introduction',5,
 'Uliza: Waingereza walichukua Tanzania lini na vipi? Baada ya tukio gani?',
 'Toa maarifa yao kuhusu jinsi Waingereza walivyochukua Tanzania.',
 'Wanafunzi wanabainisha tukio lililofanya Waingereza wachukue Tanzania.'],
[131,2,'development',20,
 'Ongoza majadiliano kuhusu jinsi Waingereza walichukua Tanzania baada ya Vita Kuu ya Kwanza (1919) kupitia Amri ya Ligi ya Mataifa: Mandate territory, later Trusteeship.',
 'Jadili jinsi Waingereza walichukua Tanzania na msingi wa kisheria wa utawala wao.',
 'Jinsi Waingereza walichukua Tanzania baada ya Vita Kuu ya Kwanza imebainishwa kwa usahihi.'],
[131,2,'design',10,
 'Vikundi vilinganishe njia Waingereza waliingia Tanzania na njia Wajerumani waliingia — tofauti na mfanano.',
 'Linganisha njia Waingereza na Wajerumani waliingia Tanzania.',
 'Tofauti na mfanano wa jinsi Waingereza na Wajerumani waliingia Tanzania zimebainishwa.'],
[131,3,'realisation',5,
 'Eleza jinsi Waingereza walivyochukua utawala wa Tanzania baada ya Vita Kuu ya Kwanza.',
 'Eleza jinsi Waingereza walivyochukua utawala wa Tanzania kwa hatua mbili.',
 'Jinsi Waingereza walichukua Tanzania imebainishwa kwa usahihi.'],

[132,2,'introduction',5,
 'Uliza: Waingereza walisimamia Tanzania tofauti na Wajerumani? Walitumia sera gani?',
 'Pendekeza tofauti za sera kati ya Waingereza na Wajerumani Tanzania.',
 'Wanafunzi wanabainisha tofauti moja ya sera kati ya Waingereza na Wajerumani.'],
[132,2,'development',20,
 'Ongoza majadiliano kuhusu sera za Waingereza: Utawala wa Wasimamizi wa Kiasili (Indirect Rule), ushuru wa kura, kilimo cha biashara, elimu ya msingi kwa Waafrika.',
 'Jadili sera za kiuchumi na kisiasa za Waingereza Tanzania na athari zake.',
 'Sera za kiuchumi na kisiasa za Waingereza Tanzania zimebainishwa kwa usahihi.'],
[132,2,'design',10,
 'Vikundi viunde jedwali linalolinganisha sera za Wajerumani na Waingereza Tanzania.',
 'Unda jedwali linalolinganisha sera za Wajerumani na Waingereza Tanzania.',
 'Jedwali sahihi linalolinganisha sera za mamlaka mbili za kikoloni limeundwa.'],
[132,3,'realisation',5,
 'Eleza sera mbili za kiuchumi na mbili za kisiasa za Waingereza Tanzania.',
 'Eleza sera mbili za kiuchumi na mbili za kisiasa za Waingereza Tanzania.',
 'Sera nne sahihi za Waingereza Tanzania zimebainishwa.'],

[133,2,'introduction',5,
 'Uliza: Utawala wa Waingereza uliathiri vipi maisha ya Watanzania wa kawaida?',
 'Pendekeza athari za utawala wa Waingereza kwa Watanzania.',
 'Wanafunzi wanabainisha athari moja ya utawala wa Waingereza.'],
[133,2,'development',20,
 'Ongoza majadiliano tathmini ya athari za Waingereza: athari chanya (elimu, afya, miundombinu) na hasi (ubaguzi wa rangi, ulipuaji ardhi, kuharibu utamaduni, ushuru mkubwa).',
 'Jadili na utathmini athari za utawala wa Kiingereza kwa Watanzania.',
 'Athari za utawala wa Kiingereza kwa Watanzania zimetathminiwa kwa usahihi.'],
[133,2,'design',10,
 'Vikundi vitathmini: Utawala wa Kiingereza ulisaidia au kudhuru Tanzania zaidi?',
 'Tathmini kwa hoja kama utawala wa Kiingereza ulisaidia au kudhuru Tanzania zaidi.',
 'Tathmini yenye hoja ya utawala wa Kiingereza kwa Tanzania imewasilishwa.'],
[133,3,'realisation',5,
 'Eleza athari mbili chanya na mbili hasi za utawala wa Kiingereza kwa Watanzania.',
 'Eleza athari mbili chanya na mbili hasi za utawala wa Kiingereza Tanzania.',
 'Athari nne sahihi za utawala wa Kiingereza zimebainishwa.'],

[134,5,'introduction',5,
 'Uliza: Mnajua chama cha TANU? Kilianzishwa lini? Na nani? Kwa kusudi gani?',
 'Toa maarifa yao ya awali kuhusu TANU na lengo lake.',
 'Wanafunzi wanabainisha maarifa ya awali kuhusu TANU.'],
[134,2,'development',20,
 'Ongoza majadiliano ya vikundi kuhusu historia ya TANU (Tanganyika African National Union): kuanzishwa 1954 na Julius Nyerere, malengo ya kupigania uhuru, mikakati yake ya amani.',
 'Jadili historia ya TANU na jukumu lake katika kupigania uhuru wa Tanzania.',
 'Historia ya TANU na jukumu lake katika harakati za uhuru zimebainishwa kwa usahihi.'],
[134,1,'design',10,
 'Onyesha picha za mikutano ya TANU na kiongozi wake. Vikundi vibainishe mkakati wa TANU wa kupata uhuru.',
 'Angalia picha za TANU na ubainishe mikakati ya TANU ya kupata uhuru.',
 'Mikakati ya TANU ya kupigania uhuru imebainishwa kwa usahihi.'],
[134,3,'realisation',5,
 'Eleza historia ya TANU na jukumu lake kuu katika kupigania uhuru wa Tanzania.',
 'Eleza historia ya TANU na jukumu lake kuu moja katika kupigania uhuru.',
 'Historia ya TANU na jukumu lake katika kupigania uhuru zimebainishwa kwa usahihi.'],

[135,1,'introduction',5,
 'Onyesha picha ya Julius Nyerere. Uliza: Mnajua mtu huyu? Alitoa mchango gani kwa Tanzania?',
 'Toa maarifa yao kuhusu Julius Nyerere na mchango wake.',
 'Wanafunzi wanabainisha maarifa ya awali kuhusu Julius Nyerere.'],
[135,2,'development',20,
 'Ongoza majadiliano ya vikundi kuhusu jukumu la Julius Nyerere: kuanzisha TANU, kuzungumza Umoja wa Mataifa, kueneza elimu ya kisiasa, kutumia mbinu za amani, kupata uhuru 1961.',
 'Jadili jukumu la Julius Nyerere katika harakati za uhuru Tanzania.',
 'Jukumu la Julius Nyerere katika harakati za uhuru Tanzania limebainishwa kwa usahihi.'],
[135,2,'design',10,
 'Vikundi viandike wasifu mfupi wa Julius Nyerere ukionyesha michango yake kwa Tanzania.',
 'Andika wasifu mfupi wa Julius Nyerere ukionyesha michango yake mitatu katika kupigania uhuru.',
 'Wasifu wenye michango sahihi ya Julius Nyerere umeandikwa.'],
[135,3,'realisation',5,
 'Eleza michango mitatu ya Julius Nyerere katika kupigania uhuru wa Tanzania.',
 'Eleza michango mitatu ya Julius Nyerere katika harakati za uhuru wa Tanzania.',
 'Michango mitatu sahihi ya Julius Nyerere katika harakati za uhuru imebainishwa.'],

// ── Sura ya Saba: Sayamsi na Teknolojia Kabla ya Ukoloni ─────────────────────

[136,5,'introduction',5,
 'Uliza: Sayamsi na teknolojia ni nini? Je, watu wa Africa ya zamani walikuwa na teknolojia?',
 'Toa mawazo yao kuhusu maana ya sayamsi na teknolojia na mifano kutoka Afrika.',
 'Wanafunzi wanabainisha maarifa ya awali kuhusu sayamsi na teknolojia.'],
[136,2,'development',20,
 'Ongoza majadiliano ya vikundi kuhusu maana ya sayamsi (utafiti wa ulimwengu kwa mbinu za utaratibu) na teknolojia (matumizi ya maarifa ya kisayansi kutengeneza zana na kutatua matatizo) katika muktadha wa historia.',
 'Jadili maana ya sayamsi na teknolojia katika muktadha wa historia na toa mifano ya Afrika.',
 'Maana ya sayamsi na teknolojia katika muktadha wa historia imebainishwa kwa usahihi.'],
[136,2,'design',10,
 'Vikundi vibainishe mifano ya sayamsi na teknolojia ya Afrika iliyokuwepo kabla ya ukoloni.',
 'Bainisha mifano mitatu ya sayamsi na teknolojia ya Afrika kabla ya ukoloni.',
 'Mifano sahihi ya sayamsi na teknolojia ya Afrika kabla ya ukoloni imebainishwa.'],
[136,3,'realisation',5,
 'Eleza maana ya sayamsi na teknolojia kwa maneno yako mwenyewe.',
 'Eleza maana ya sayamsi na teknolojia kwa sentensi mbili.',
 'Maana ya sayamsi na teknolojia imebainishwa kwa usahihi.'],

[137,2,'introduction',5,
 'Uliza: Sayamsi na teknolojia zinahusiana vipi na maendeleo ya jamii? Bila teknolojia ungekuwa ukiishi vipi?',
 'Jadili jinsi teknolojia inavyoathiri maisha ya kila siku.',
 'Wanafunzi wanabainisha uhusiano wa msingi kati ya teknolojia na maisha.'],
[137,2,'development',20,
 'Ongoza majadiliano ya vikundi kuhusu uhusiano kati ya sayamsi, teknolojia na maendeleo ya jamii: sayamsi hufanya uvumbuzi → teknolojia huitumia → jamii inafaidika.',
 'Jadili uhusiano kati ya sayamsi, teknolojia na maendeleo ya jamii na toa mifano kutoka historia.',
 'Uhusiano kati ya sayamsi, teknolojia na maendeleo ya jamii umebainishwa kwa usahihi.'],
[137,4,'design',10,
 'Vikundi viunde mchoro unaoonesha uhusiano wa sayamsi → teknolojia → maendeleo ya jamii na wape mifano halisi.',
 'Unda mchoro unaoonesha uhusiano wa sayamsi, teknolojia na maendeleo ya jamii.',
 'Mchoro sahihi wa uhusiano wa sayamsi, teknolojia na maendeleo umeundwa.'],
[137,3,'realisation',5,
 'Eleza kwa mfano mmoja jinsi sayamsi na teknolojia vilivyosaidia maendeleo ya jamii za Afrika za zamani.',
 'Eleza kwa mfano mmoja jinsi sayamsi na teknolojia vilisaidia jamii za Afrika za zamani.',
 'Mfano sahihi wa uhusiano wa sayamsi, teknolojia na maendeleo ya jamii umebainishwa.'],

[138,1,'introduction',5,
 'Onyesha picha za zana za mawe za Zama za Mawe za Kale. Uliza: Hizi zilitengenezwaje na zilitumika kwa nini?',
 'Angalia picha na pendekeza jinsi zana hizo zilivyotengenezwa na kutumika.',
 'Wanafunzi wanabainisha zana za mawe na matumizi yake ya msingi.'],
[138,2,'development',20,
 'Ongoza majadiliano ya vikundi kuhusu aina za zana za Zama za Mawe za Kale: vijembe vya mawe (hand axes), visu, nguruwe za mawe — jinsi zilivyotengenezwa kwa kupigapiga mawe.',
 'Jadili aina za zana za Zama za Mawe, jinsi zilivyotengenezwa na kila zana ilitumika kwa nini.',
 'Aina za zana za Zama za Mawe za Kale zimebainishwa na kuelezwa jinsi zilivyotengenezwa.'],
[138,4,'design',10,
 'Vikundi vichoree zana tatu za Zama za Mawe za Kale na vieleze jinsi zilivyotengenezwa na kutumika.',
 'Chora zana tatu za Zama za Mawe za Kale na eleza jinsi zilivyotengenezwa na kutumika.',
 'Zana tatu za Zama za Mawe zimechorwa na kuelezwa kwa usahihi.'],
[138,3,'realisation',5,
 'Orodhesha zana tatu za Zama za Mawe za Kale na eleza matumizi ya kila moja.',
 'Orodhesha zana tatu za Zama za Mawe za Kale na eleza matumizi ya kila zana.',
 'Zana tatu za Zama za Mawe na matumizi yake zimebainishwa kwa usahihi.'],

[139,3,'introduction',5,
 'Uliza: Binadamu wa Zama za Mawe alilaa nini? Aliishi wapi? Alikuwa akilima ardhi?',
 'Pendekeza jinsi binadamu wa Zama za Mawe alivyojipatia chakula na makazi.',
 'Wanafunzi wanabainisha maarifa ya awali kuhusu maisha ya Zama za Mawe.'],
[139,2,'development',20,
 'Ongoza majadiliano ya vikundi kuhusu njia za binadamu wa Zama za Mawe za Kale kujipatia chakula (uwindaji na ukusanyaji) na makazi (mapango, miti).',
 'Jadili njia za binadamu wa Zama za Mawe kujipatia chakula na makazi na uandike muhtasari.',
 'Njia za binadamu wa Zama za Mawe kujipatia chakula na makazi zimebainishwa kwa usahihi.'],
[139,4,'design',10,
 'Vikundi vichoree na vieleze siku ya kawaida ya binadamu wa Zama za Mawe — asubuhi, mchana, jioni.',
 'Chora na ueleze siku ya kawaida ya binadamu wa Zama za Mawe za Kale.',
 'Siku ya kawaida ya binadamu wa Zama za Mawe imechorwa na kuelezwa kwa usahihi.'],
[139,3,'realisation',5,
 'Eleza njia mbili za binadamu wa Zama za Mawe kujipatia chakula na njia moja ya kupata makazi.',
 'Eleza njia mbili za binadamu wa Zama za Mawe kujipatia chakula na njia moja ya kupata makazi.',
 'Njia za binadamu wa Zama za Mawe kujipatia chakula na makazi zimebainishwa.'],

[140,1,'introduction',5,
 'Onyesha kipande cha chuma na mawe. Uliza: Tofauti kati ya zana za chuma na mawe ni nini? Ni ipi bora zaidi?',
 'Linganisha chuma na mawe na eleza kwa nini moja inaweza kuwa bora kuliko nyingine.',
 'Wanafunzi wanabainisha tofauti za msingi kati ya chuma na mawe.'],
[140,2,'development',20,
 'Ongoza majadiliano ya vikundi kuhusu uvumbuzi wa chuma: jinsi chuma kilivyogunduliwa, kuyeyushwa na kutumika kutengeneza zana bora. Eleza athari za uvumbuzi huu kwa teknolojia.',
 'Jadili uvumbuzi wa chuma na athari zake kwa maendeleo ya teknolojia ya binadamu.',
 'Uvumbuzi wa chuma na athari zake kwa teknolojia zimebainishwa kwa usahihi.'],
[140,1,'design',10,
 'Onyesha mchakato wa kuyeyusha chuma (kwa picha). Vikundi vibainishe hatua za kuyeyusha chuma na kufanya zana.',
 'Angalia picha za mchakato wa kuyeyusha chuma na ubainishe hatua za kutengeneza zana za chuma.',
 'Mchakato wa kutengeneza zana za chuma umebainishwa kwa usahihi.'],
[140,3,'realisation',5,
 'Eleza uvumbuzi wa chuma na athari yake moja kuu kwa maendeleo ya teknolojia.',
 'Eleza uvumbuzi wa chuma na athari yake moja kuu kwa teknolojia ya binadamu.',
 'Uvumbuzi wa chuma na athari yake kwa teknolojia imebainishwa kwa usahihi.'],

[141,2,'introduction',5,
 'Uliza: Chuma kilitumiwa kutengeneza nini? Zana hizi zinaweza kutengenezwa na mawe pia?',
 'Pendekeza zana na silaha zinazoweza kutengenezwa kwa chuma.',
 'Wanafunzi wanabainisha zana na silaha za msingi za chuma.'],
[141,2,'development',20,
 'Ongoza majadiliano ya vikundi kuhusu zana za chuma: majembe, miunzi, visu, shoka, mikuki, panga — na jinsi zinavyotofautiana na zana za mawe kwa ubora na ufanisi.',
 'Jadili zana na silaha zilizotengenezwa kutoka chuma na uziorodheshe kwa mifano.',
 'Zana na silaha za chuma zimebainishwa na kuelezwa jinsi zinavyotofautiana na za mawe.'],
[141,4,'design',10,
 'Vikundi vichoree zana na silaha tano za chuma na vieleze matumizi ya kila moja.',
 'Chora zana na silaha tano za chuma na eleza matumizi ya kila moja.',
 'Zana na silaha tano za chuma zimechorwa na matumizi yake yameelezwa.'],
[141,3,'realisation',5,
 'Orodhesha zana tatu na silaha mbili zilizotengenezwa kutoka chuma na eleza matumizi ya kila moja.',
 'Orodhesha zana tatu na silaha mbili za chuma na eleza matumizi ya kila moja.',
 'Zana tatu na silaha mbili za chuma zimeorodheshwa na matumizi yake yamebainishwa.'],

[142,6,'introduction',5,
 'Uliza: Jinsi gani teknolojia ya Zama za Chuma ilikuwa tofauti na ile ya Zama za Mawe? Bora zaidi vipi?',
 'Pendekeza tofauti tatu kati ya teknolojia ya Zama za Mawe na Zama za Chuma.',
 'Wanafunzi wanabainisha tofauti za msingi kati ya Zama za Mawe na Chuma.'],
[142,2,'development',20,
 'Ongoza majadiliano ya vikundi kulinganisha teknolojia ya Zama za Mawe (zana ghafi, ngumu kufanya, haziachi ukali) na Zama za Chuma (zana nyepesi, zenye ukali, zinaweza kufanywa upya).',
 'Jadili na uandike jedwali la ulinganisho wa teknolojia ya Zama za Mawe na Zama za Chuma.',
 'Teknolojia ya Zama za Mawe na Zama za Chuma imelinganishwa kwa usahihi.'],
[142,6,'design',10,
 'Fikiri-andika-jozisha-shirikisha: Kila mwanafunzi abainishe tofauti mbili, ajozishe na mwenzake, wasilishane.',
 'Andika tofauti mbili kati ya Zama za Mawe na Zama za Chuma, jozisha na shirikisha.',
 'Tofauti sahihi mbili kati ya Zama za Mawe na Zama za Chuma zimebainishwa.'],
[142,3,'realisation',5,
 'Eleza tofauti tatu kati ya teknolojia ya Zama za Mawe na Zama za Chuma.',
 'Eleza tofauti tatu kati ya teknolojia ya Zama za Mawe na Zama za Chuma.',
 'Tofauti tatu sahihi kati ya teknolojia ya Zama hizo zimebainishwa.'],

[143,3,'introduction',5,
 'Uliza: Teknolojia ya chuma ilibadilisha maisha ya binadamu vipi? Watu walianza kufanya nini ambacho hawakuweza kufanya kabla?',
 'Pendekeza jinsi teknolojia ya chuma ilibadilisha maisha ya watu.',
 'Wanafunzi wanabainisha mabadiliko mawili yaliyotokea kutokana na uvumbuzi wa chuma.'],
[143,2,'development',20,
 'Ongoza majadiliano ya vikundi kuhusu jinsi teknolojia ya chuma ilivyobadilisha maisha: kilimo bora (majembe ya chuma), vita vya mara nyingi zaidi (silaha bora), biashara ya zana, makazi ya kudumu.',
 'Jadili jinsi teknolojia ya chuma ilivyobadilisha maisha ya binadamu na uandike mifano.',
 'Jinsi teknolojia ya chuma ilivyobadilisha maisha ya binadamu imebainishwa kwa usahihi.'],
[143,2,'design',10,
 'Vikundi viunde mstari wa muda unaoonyesha mabadiliko makuu yaliyotokea wakati wa Zama za Chuma.',
 'Unda mstari wa muda unaoonyesha mabadiliko makuu ya Zama za Chuma.',
 'Mstari wa muda wenye mabadiliko sahihi ya Zama za Chuma umeundwa.'],
[143,3,'realisation',5,
 'Eleza jinsi teknolojia ya chuma ilivyobadilisha maisha ya binadamu kwa mifano miwili.',
 'Eleza jinsi teknolojia ya chuma ilivyobadilisha maisha ya binadamu kwa mifano miwili.',
 'Mifano miwili sahihi ya mabadiliko ya teknolojia ya chuma imebainishwa.'],

[144,5,'introduction',5,
 'Uliza: Je, Afrika ilikuwa na uvumbuzi wake wa sayamsi na teknolojia kabla ya ukoloni? Uvumbuzi gani?',
 'Toa mifano ya uvumbuzi wowote wa Afrika wanaoufahamu.',
 'Wanafunzi wanabainisha maarifa ya awali kuhusu uvumbuzi wa Afrika.'],
[144,2,'development',20,
 'Ongoza majadiliano ya vikundi kuhusu vichangio vya jamii za Kiafrika: ufumbuzi wa madini, usanifu wa majengo (Zimbabwe), kilimo, dawa za asili, hisabati (hifadhi ya Ishango), usafiri wa baharini.',
 'Jadili mchango wa jamii za Kiafrika katika sayamsi na teknolojia kabla ya ukoloni.',
 'Mchango wa jamii za Kiafrika katika sayamsi na teknolojia umebainishwa kwa usahihi.'],
[144,12,'design',10,
 'Vikundi vitafiti uvumbuzi mmoja wa Afrika na viwasilishe matokeo kwa darasa.',
 'Tafiti uvumbuzi mmoja wa kisayamsi au kiteknolojia kutoka Afrika na uwasilishe matokeo.',
 'Uvumbuzi wa Afrika wa kisayamsi au kiteknolojia umetafitishwa na kuwasilishwa kwa usahihi.'],
[144,3,'realisation',5,
 'Eleza mchango wa Afrika katika sayamsi na teknolojia kwa mifano miwili.',
 'Eleza mchango wa jamii za Kiafrika katika sayamsi na teknolojia kwa mifano miwili.',
 'Mchango wa Afrika katika sayamsi na teknolojia umebainishwa kwa mifano miwili sahihi.'],

[145,2,'introduction',5,
 'Uliza: Uvumbuzi wa sayamsi na teknolojia wa Afrika wa zamani una umuhimu gani kwa Tanzania ya leo?',
 'Pendekeza umuhimu wa kujua kuhusu teknolojia ya Afrika ya zamani.',
 'Wanafunzi wanabainisha umuhimu wa awali wa teknolojia ya kabla ya ukoloni.'],
[145,2,'development',20,
 'Ongoza majadiliano tathmini ya umuhimu wa vichangio vya teknolojia ya kabla ya ukoloni: kuimarisha utambulisho wa Afrika, kuonyesha uwezo wa Waafrika wa kujitegemea, kutumika kama msingi wa teknolojia ya kisasa.',
 'Jadili na utathmini umuhimu wa vichangio vya teknolojia ya kabla ya ukoloni kwa Tanzania ya leo.',
 'Umuhimu wa vichangio vya teknolojia ya kabla ya ukoloni kwa Tanzania umetathminiwa kwa usahihi.'],
[145,2,'design',10,
 'Vikundi viunde hoja: "Kujifunza kuhusu teknolojia ya kabla ya ukoloni ni muhimu kwa Tanzania ya sasa." Wasilisha na jadiliana.',
 'Unda hoja tatu za kwa nini kujifunza teknolojia ya kabla ya ukoloni ni muhimu kwa Tanzania ya sasa.',
 'Hoja zenye mantiki za umuhimu wa teknolojia ya kabla ya ukoloni zimeundwa.'],
[145,3,'realisation',5,
 'Tathmini umuhimu wa vichangio vya teknolojia ya kabla ya ukoloni kwa Tanzania kwa sentensi tatu.',
 'Tathmini umuhimu wa vichangio vya teknolojia ya kabla ya ukoloni kwa Tanzania kwa sentensi tatu.',
 'Tathmini sahihi ya umuhimu wa teknolojia ya kabla ya ukoloni imeandikwa.'],

];

$db->beginTransaction();
try {
    $count = 0;
    foreach ($data as $r) { $ins->execute($r); $count++; }
    $db->commit();
    echo "Inserted $count element_methods rows for Historia ya Tanzania.\n";
} catch (Exception $e) {
    $db->rollBack();
    echo "ERROR: " . $e->getMessage() . "\n";
}
