<?php
// Seed element_methods for Mathematics Form I (elements 146-178)
require __DIR__ . '/../config/db.php';
$db = getDB();
$db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

$ins = $db->prepare("INSERT INTO element_methods
    (element_id,method_id,stage,time_minutes,teaching_activity,learning_activity,assessment_criteria)
    VALUES (?,?,?,?,?,?,?)");

// method_ids: 5=Brainstorming,7=Case Study,1=Demonstration,11=Field Visit,
// 2=Group Discussion,4=Hands-on,9=Practical,8=Project,3=Q&A,12=Research,10=Role Play,6=Think-Pair-Share

$data = [

// ── Ch1: Concept of Mathematics ──────────────────────────────────────────────

// 146: Define Mathematics and explain its role in everyday life
[146,5,'introduction',5,
 'Brainstorm: Ask students "What is Mathematics?" and "Where do you use Mathematics in everyday life?" Record responses on the board.',
 'Share ideas about what Mathematics means and where they encounter it daily (shopping, cooking, time, etc.).',
 'Students can give at least two examples of Mathematics in everyday life.'],
[146,2,'development',20,
 'Guide a group discussion using handouts showing real-life scenarios involving Mathematics: a market receipt, a recipe, a timetable. Ask students to identify the mathematical operations involved.',
 'Discuss in groups the mathematical operations found in each real-life scenario and identify the role Mathematics plays.',
 'The role of Mathematics in everyday life is clearly explained with relevant examples from the scenarios.'],
[146,2,'design',10,
 'Each group creates a poster or list showing at least five real-life situations where Mathematics is used, with the specific mathematical concepts involved.',
 'Create a list of five real-life situations and the Mathematics involved in each situation.',
 'At least five real-life situations using Mathematics are identified with correct mathematical concepts.'],
[146,3,'realisation',5,
 'Each student writes a definition of Mathematics in their own words and states two ways Mathematics is used in everyday life.',
 'Write a definition of Mathematics and two ways it is used in everyday life.',
 'Mathematics is correctly defined and two relevant everyday uses are stated.'],

// 147: Explain the history and development of Mathematics
[147,12,'introduction',5,
 'Ask: "Who invented Mathematics? Where and when was Mathematics first used?" Allow students to speculate.',
 'Share their ideas about the origins of Mathematics.',
 'Students show curiosity about the history of Mathematics.'],
[147,2,'development',20,
 'Guide a group discussion using handouts about the history of Mathematics: ancient Egypt (geometry for land measurement), Mesopotamia (arithmetic), Greece (formal proofs), Arabia (algebra), and modern developments.',
 'Read the handout and discuss the key stages in the development of Mathematics across different civilizations.',
 'Key stages in the history and development of Mathematics are correctly identified.'],
[147,12,'design',10,
 'Groups research one ancient civilization that contributed to Mathematics and create a timeline entry with their contribution.',
 'Research one ancient civilization\'s contribution to Mathematics and prepare a brief presentation.',
 'The mathematical contribution of an ancient civilization is correctly researched and presented.'],
[147,3,'realisation',5,
 'Each student lists three civilizations that contributed to the development of Mathematics and one contribution from each.',
 'List three civilizations and one mathematical contribution from each.',
 'Three civilizations and their mathematical contributions are correctly listed.'],

// 148: Identify branches of Mathematics and their applications
[148,5,'introduction',5,
 'Ask: "What types of Mathematics have you heard of? Arithmetic? Algebra? Geometry? Statistics?" Record responses.',
 'Brainstorm the different types of Mathematics they have heard of.',
 'Students can name at least two branches of Mathematics.'],
[148,2,'development',20,
 'Guide groups to explore the main branches of Mathematics (Arithmetic, Algebra, Geometry, Statistics, Calculus) and discuss real-life applications of each branch.',
 'Discuss each branch of Mathematics, its definition, and two real-life applications. Fill in the provided table.',
 'The main branches of Mathematics and their applications are correctly identified.'],
[148,6,'design',10,
 'Think-pair-share: Each student chooses a branch they find most interesting and explains why to their partner, then shares with the class.',
 'Choose a branch of Mathematics, explain why you find it interesting, pair with a partner and share with the class.',
 'A branch of Mathematics is correctly identified and its relevance is explained.'],
[148,3,'realisation',5,
 'Each student names four branches of Mathematics and one application of each.',
 'Name four branches of Mathematics and one application of each branch.',
 'Four branches of Mathematics and one application each are correctly stated.'],

// 149: Relate Mathematics to other subjects (Physics, Chemistry, Geography, etc.)
[149,5,'introduction',5,
 'Ask: "Which other school subjects use Mathematics? How?" Allow students to think and share.',
 'Share ideas about which subjects use Mathematics and how.',
 'Students can name two subjects that use Mathematics.'],
[149,2,'development',20,
 'Guide a jigsaw activity: divide the class into expert groups, each assigned a subject (Physics, Chemistry, Biology, Geography, Business). Groups discuss and then regroup to share how Mathematics is used in their subject.',
 'In expert groups discuss how Mathematics is used in your assigned subject. Regroup and share findings.',
 'The relationship between Mathematics and at least three other subjects is correctly explained.'],
[149,2,'design',10,
 'Groups create a mind map showing Mathematics at the centre and connected subjects around it with specific examples of how Mathematics is used.',
 'Create a mind map showing how Mathematics connects to at least four other school subjects with specific examples.',
 'A mind map correctly showing the relationship between Mathematics and other subjects is created.'],
[149,3,'realisation',5,
 'Each student explains in two sentences how Mathematics is used in one subject of their choice.',
 'Explain in two sentences how Mathematics is used in one other school subject.',
 'The correct use of Mathematics in another school subject is explained.'],

// ── Ch2: Approximations and Estimation ───────────────────────────────────────

// 150: Round off numbers to given significant figures and decimal places
[150,1,'introduction',5,
 'Demonstrate rounding off on the board: round 3.746 to 2 decimal places and to 2 significant figures. Show the steps clearly.',
 'Watch the demonstration and attempt to identify the rule for rounding off.',
 'Students can identify the basic rule for rounding off (5 and above, round up).'],
[150,2,'development',20,
 'Guide groups using a worksheet with numbers to round off to various significant figures and decimal places. Circulate and provide guidance. Groups compare answers.',
 'Work in groups to round off the given numbers to the required significant figures and decimal places.',
 'Numbers are correctly rounded off to the required significant figures and decimal places.'],
[150,9,'design',10,
 'Students work individually on a set of problems: round off measurements (lengths, masses, prices) to given significant figures and decimal places.',
 'Round off the given measurements to the required number of significant figures and decimal places.',
 'Measurements are correctly rounded off to the required precision.'],
[150,3,'realisation',5,
 'Pose two questions: round 4.8756 to 2 decimal places and to 3 significant figures. Students answer individually.',
 'Round 4.8756 to 2 decimal places and to 3 significant figures.',
 '4.8756 is correctly rounded to 2 decimal places (4.88) and to 3 significant figures (4.88).'],

// 151: Estimate values using approximation techniques
[151,5,'introduction',5,
 'Brainstorm: "When do we estimate rather than calculate exactly? Give examples from real life." Record student responses.',
 'Share situations where estimation is used (estimating cost, time, distance).',
 'Students give at least two real-life situations where estimation is used.'],
[151,2,'development',20,
 'Guide group discussion using scenarios: estimate the cost of items in a market, estimate the number of students in a school photograph, estimate the length of a room using strides. Discuss estimation strategies.',
 'Discuss estimation strategies for each scenario and record estimated values with reasoning.',
 'Appropriate estimation strategies are applied and reasonable estimated values are obtained.'],
[151,9,'design',10,
 'Students estimate answers to real-life problems (e.g., how many tiles needed to cover a floor, approximate cost of school supplies) using front-end estimation or rounding.',
 'Use approximation to estimate answers to the given real-life problems without a calculator.',
 'Reasonable estimates are obtained using correct approximation techniques.'],
[151,3,'realisation',5,
 'Pose a problem: Estimate the cost of 4 items priced at Tsh 1,950, Tsh 3,100, Tsh 780, and Tsh 2,450. Students estimate the total.',
 'Estimate the total cost of four items by rounding each price to the nearest thousand.',
 'A reasonable estimate of the total cost is correctly obtained through approximation.'],

// 152: Calculate percentage error in approximations
[152,1,'introduction',5,
 'Demonstrate: the actual length of a pencil is 15.2 cm, you estimated 15 cm. Show how to find the error and percentage error.',
 'Watch the demonstration and try to identify the formula for percentage error.',
 'Students can state the formula for percentage error: (error/actual value) × 100%.'],
[152,2,'development',20,
 'Guide groups through examples of calculating absolute error and percentage error in different contexts (measurement of length, mass, temperature). Use worksheet.',
 'Calculate absolute error and percentage error for the measurements given in the worksheet.',
 'Absolute error and percentage error are correctly calculated for each measurement.'],
[152,9,'design',10,
 'Students solve problems: given approximate and actual values, calculate the percentage error and determine if the approximation is acceptable.',
 'Calculate the percentage error for each approximation and state if it is acceptable (< 5%).',
 'Percentage errors are correctly calculated and correctly assessed as acceptable or not.'],
[152,3,'realisation',5,
 'Pose: actual mass = 2.48 kg, estimated = 2.5 kg. Find the percentage error.',
 'Calculate the percentage error when actual mass = 2.48 kg and estimated mass = 2.5 kg.',
 'Percentage error is correctly calculated as approximately 0.81%.'],

// 153: Apply approximation to solve real-life problems
[153,7,'introduction',5,
 'Present a case: A contractor estimates the cost of building materials to be Tsh 500,000. The actual cost is Tsh 485,000. Ask: Was the estimate good? How would you decide?',
 'Analyse the case and explain whether the estimate was acceptable and how you know.',
 'Students can use the concept of percentage error to evaluate the estimate.'],
[153,2,'development',20,
 'Guide groups to solve real-life approximation problems: budgeting for a school event, estimating travel time, approximating ingredient quantities for cooking. Apply rounding and percentage error.',
 'Solve the real-life approximation problems in your group, showing your estimation method and percentage error where appropriate.',
 'Real-life approximation problems are correctly solved using appropriate estimation techniques.'],
[153,9,'design',10,
 'Each group creates a real-life problem involving approximation and exchanges it with another group to solve.',
 'Create a real-life problem involving approximation and solve the problem given by another group.',
 'Real-life approximation problems are correctly created and solved.'],
[153,3,'realisation',5,
 'Pose: estimate how many 250 ml cups can be filled from a 3-litre bottle. State your answer and percentage error if actual answer is given.',
 'Estimate how many 250 ml cups fill a 3-litre bottle and calculate the percentage error.',
 'Correct estimate (12 cups) is obtained and percentage error is correctly calculated.'],

// ── Ch3: Rates and Proportions ────────────────────────────────────────────────

// 154: Define and calculate rates (speed, flow rate, unit price)
[154,1,'introduction',5,
 'Demonstrate: A car travels 120 km in 2 hours. Ask: How fast is it going? Show the calculation of speed = distance/time.',
 'Watch the demonstration and try to state the formula for rate (speed).',
 'Students can state that rate = quantity per unit of time or per unit.'],
[154,2,'development',20,
 'Guide groups to calculate different types of rates from real-life scenarios: speed (km/h), water flow (litres/minute), unit price (Tsh/kg), fuel consumption (km/litre).',
 'Calculate the rate for each real-life scenario in your group and state the unit of the rate.',
 'Different types of rates are correctly calculated with correct units stated.'],
[154,9,'design',10,
 'Students solve individual problems: calculate speed, unit price, and flow rate from given data.',
 'Calculate speed, unit price, and flow rate from the given data, stating units clearly.',
 'Speed, unit price, and flow rate are correctly calculated with correct units.'],
[154,3,'realisation',5,
 'Pose: A pump fills a 1,000-litre tank in 25 minutes. What is the flow rate in litres per minute?',
 'Calculate the flow rate of the pump.',
 'Flow rate is correctly calculated as 40 litres per minute.'],

// 155: Solve problems involving ratios
[155,5,'introduction',5,
 'Brainstorm: "Where do we use ratios in real life?" — mixing cement (3:1), sharing items, map scales, recipes.',
 'Share examples of where ratios are used in everyday life.',
 'Students can give two examples of ratios from everyday life.'],
[155,2,'development',20,
 'Guide groups through ratio problems: simplifying ratios, dividing quantities in given ratios, and comparing ratios. Use concrete examples (sharing money, mixing paint colours, cement and sand).',
 'Solve ratio problems in groups: simplify the given ratios and divide the given quantity in the stated ratios.',
 'Ratios are correctly simplified and quantities are correctly divided in given ratios.'],
[155,9,'design',10,
 'Students solve practical problems: a recipe for 4 people requires 200g flour — how much for 6 people? A map scale is 1:50,000 — find the actual distance for a 4 cm map distance.',
 'Solve the practical ratio problems involving recipes, map scales, and sharing.',
 'Practical ratio problems are correctly solved with clear working shown.'],
[155,3,'realisation',5,
 'Pose: Share Tsh 6,000 between Ali and Bea in the ratio 2:3. How much does each get?',
 'Divide Tsh 6,000 between Ali and Bea in the ratio 2:3.',
 'Ali gets Tsh 2,400 and Bea gets Tsh 3,600. Calculation is correctly shown.'],

// 156: Distinguish between direct and inverse proportion
[156,1,'introduction',5,
 'Demonstrate with a table: as the number of items increases, the total cost increases (direct) vs. as the number of workers increases, time to complete a task decreases (inverse). Show the patterns.',
 'Observe the two tables and try to identify the difference between the two proportions.',
 'Students can identify the basic difference between direct and inverse proportion.'],
[156,2,'development',20,
 'Guide group discussion: classify given scenarios as direct or inverse proportion, and explain why. Scenarios: more petrol → more distance; more workers → less time; more items → more cost; more speed → less time.',
 'Classify each scenario as direct or inverse proportion and explain the reasoning.',
 'Scenarios are correctly classified as direct or inverse proportion with correct reasoning.'],
[156,6,'design',10,
 'Think-pair-share: Each student creates one example of direct proportion and one of inverse proportion from real life, then shares with partner and class.',
 'Create one real-life example each of direct and inverse proportion, share with partner, then with class.',
 'Correct and relevant examples of both direct and inverse proportion are created.'],
[156,3,'realisation',5,
 'Pose two scenarios and ask students to classify each as direct or inverse: (a) cost of fuel vs. litres purchased; (b) time to paint a house vs. number of painters.',
 'Classify each scenario as direct or inverse proportion and explain why.',
 'Both scenarios are correctly classified: (a) direct, (b) inverse, with correct explanations.'],

// 157: Solve problems on direct and inverse proportion
[157,1,'introduction',5,
 'Demonstrate solving a direct proportion problem: 5 kg of rice costs Tsh 10,000. What does 8 kg cost? Show the unitary method and ratio method.',
 'Watch the demonstration and identify the two methods for solving direct proportion problems.',
 'Students can use the unitary method to solve a simple direct proportion problem.'],
[157,2,'development',20,
 'Guide groups to solve direct and inverse proportion problems using the unitary method. Problems include: cooking ingredients, travel time, workers and time, purchasing different quantities.',
 'Solve the direct and inverse proportion problems using the unitary method. Show all working.',
 'Direct and inverse proportion problems are correctly solved using the unitary method.'],
[157,9,'design',10,
 'Students solve a set of mixed direct and inverse proportion problems independently, showing all working.',
 'Solve the mixed proportion problems independently, showing all working clearly.',
 'Mixed proportion problems are correctly solved with full working shown.'],
[157,3,'realisation',5,
 'Pose: 4 workers take 6 days to build a wall. How long would 3 workers take (inverse proportion)?',
 'Calculate how long 3 workers take to build the same wall.',
 '3 workers correctly calculated to take 8 days. Full working is shown.'],

// 158: Apply rates and proportions to real-life contexts
[158,7,'introduction',5,
 'Case study: A household uses 80 litres of water per day at a rate of Tsh 500 per 20 litres. Calculate the monthly water bill. What if they reduce usage by 25%?',
 'Analyse the case study and calculate the monthly water bill and the saving from reduced usage.',
 'Students correctly apply rate and proportion concepts to calculate water bills.'],
[158,2,'development',20,
 'Guide groups to solve comprehensive real-life problems involving both rates and proportions: foreign exchange, mixing medicines, construction materials, comparing unit prices at shops.',
 'Solve the real-life problems involving rates and proportions and present solutions to the class.',
 'Real-life problems involving rates and proportions are correctly solved with clear reasoning.'],
[158,9,'design',10,
 'Groups create and solve their own real-life rate-and-proportion problem related to their community (farming, small business, cooking, transport).',
 'Create and solve a real-life problem using rates or proportions from your community context.',
 'A relevant real-life problem is correctly created and solved using rates or proportions.'],
[158,3,'realisation',5,
 'Pose: A car travels 360 km on 40 litres of petrol. At Tsh 2,500 per litre, how much does a 270 km journey cost?',
 'Calculate the cost of the 270 km journey using rates and proportions.',
 'Journey cost is correctly calculated as Tsh 18,750. Full working is shown.'],

// ── Ch4: Fractions, Decimals and Percentages ──────────────────────────────────

// 159: Convert between fractions, decimals and percentages
[159,1,'introduction',5,
 'Demonstrate conversions on the board: 3/4 = 0.75 = 75%. Show the steps for each conversion direction.',
 'Watch the conversions and try to identify the rule for each conversion direction.',
 'Students can convert a simple fraction to a decimal and to a percentage.'],
[159,2,'development',20,
 'Guide groups to practice conversions using a table worksheet: given fraction, find decimal and percentage; given decimal, find fraction and percentage; given percentage, find fraction and decimal.',
 'Complete the conversion table for the given fractions, decimals and percentages.',
 'Conversions between fractions, decimals and percentages are correctly performed.'],
[159,9,'design',10,
 'Students complete individual conversion problems including fractions with denominators that are not powers of 10 (e.g., 1/3, 2/7).',
 'Convert the given fractions, decimals and percentages, including recurring decimals.',
 'Conversions including fractions producing recurring decimals are correctly performed.'],
[159,3,'realisation',5,
 'Convert: (a) 3/8 to decimal and percentage; (b) 0.35 to fraction and percentage; (c) 45% to fraction and decimal.',
 'Convert the given values between fraction, decimal and percentage form.',
 'All three conversions are correctly performed: (a) 0.375 / 37.5%; (b) 7/20 / 35%; (c) 9/20 / 0.45.'],

// 160: Add and subtract fractions and mixed numbers
[160,1,'introduction',5,
 'Demonstrate using fraction bars/strips: 1/2 + 1/3. Show how to find the LCM and add the fractions. Explain using visual models.',
 'Use fraction strips to model 1/2 + 1/3 and observe the demonstration.',
 'Students can add simple fractions using the LCM method.'],
[160,4,'development',20,
 'Guide groups using fraction strips and calculation to add and subtract fractions with unlike denominators and mixed numbers. Work through increasingly complex examples.',
 'Use fraction strips and calculation to add and subtract fractions and mixed numbers in the worksheet.',
 'Fractions and mixed numbers are correctly added and subtracted, with LCM correctly found.'],
[160,9,'design',10,
 'Students solve individual problems involving addition and subtraction of fractions and mixed numbers, including real-life contexts (recipes, distances).',
 'Solve the fraction addition and subtraction problems, showing all working including LCM steps.',
 'Fraction addition and subtraction problems are correctly solved with all steps shown.'],
[160,3,'realisation',5,
 'Calculate: 2¾ + 1⅔ − ½.',
 'Calculate 2¾ + 1⅔ − ½, showing all working.',
 'Answer 3 11/12 is correctly obtained with all working clearly shown.'],

// 161: Multiply and divide fractions and mixed numbers
[161,1,'introduction',5,
 'Demonstrate: 2/3 × 3/4 = 6/12 = 1/2. Then show division: 2/3 ÷ 3/4 = 2/3 × 4/3 = 8/9. Explain the "flip and multiply" rule for division.',
 'Watch the demonstrations and state in your own words the rule for dividing fractions.',
 'Students can state the rule for dividing fractions (multiply by the reciprocal).'],
[161,2,'development',20,
 'Guide groups to multiply and divide fractions and mixed numbers, using simplification before multiplying. Work through problems with increasing complexity.',
 'Multiply and divide the fractions and mixed numbers in the worksheet, simplifying where possible.',
 'Fractions and mixed numbers are correctly multiplied and divided with simplification shown.'],
[161,9,'design',10,
 'Students solve real-life problems involving multiplication and division of fractions: dividing ingredients, cutting material, sharing portions.',
 'Solve the real-life fraction multiplication and division problems, showing all working.',
 'Real-life fraction problems are correctly solved with full working shown.'],
[161,3,'realisation',5,
 'Calculate: 1⅔ × 2¼ ÷ ½.',
 'Calculate 1⅔ × 2¼ ÷ ½, showing all working.',
 'Answer 7½ is correctly obtained with all working clearly shown.'],

// 162: Solve problems involving percentages (increase, decrease, profit, loss)
[162,5,'introduction',5,
 'Brainstorm: "Where do we see percentages in real life?" — bank interest, discounts, exam marks, VAT, profit margins.',
 'Share real-life examples where percentages are used.',
 'Students give at least three real-life examples of percentages.'],
[162,2,'development',20,
 'Guide group discussion and problem solving: calculate percentage increase/decrease (prices, population), profit and loss percentage, simple interest.',
 'Solve problems on percentage increase, decrease, profit, loss, and simple interest in your group.',
 'Percentage increase, decrease, profit, loss, and simple interest are correctly calculated.'],
[162,9,'design',10,
 'Students solve individual percentage problems in context: a shopkeeper buys goods at Tsh 8,000 and sells at Tsh 10,000 — find profit % and selling price with 15% VAT.',
 'Solve the percentage problems in context, showing all working.',
 'Percentage problems in context are correctly solved with full working shown.'],
[162,3,'realisation',5,
 'A phone cost Tsh 150,000. It is sold at Tsh 120,000. Find the percentage loss.',
 'Calculate the percentage loss on the phone sale.',
 'Percentage loss correctly calculated as 20%. Full working shown.'],

// 163: Apply fractions, decimals and percentages to financial contexts
[163,7,'introduction',5,
 'Case study: A shop bought 50 kg of rice at Tsh 60,000. It sold ⅔ at a 25% profit and the rest at a 10% loss. Find the total revenue.',
 'Analyse the case study and calculate the total revenue, showing all working.',
 'Students correctly apply fractions and percentages to a multi-step financial problem.'],
[163,2,'development',20,
 'Guide groups to solve financial problems involving fractions, decimals and percentages: bank loans, tax calculations, discounts, salary deductions, business profits.',
 'Solve the financial problems involving fractions, decimals and percentages in your group.',
 'Financial problems combining fractions, decimals and percentages are correctly solved.'],
[163,9,'design',10,
 'Groups create a real-life financial problem involving fractions and percentages and exchange with another group to solve.',
 'Create a financial problem using fractions and percentages and solve the problem given by another group.',
 'Financial problems are correctly created and solved using fractions and percentages.'],
[163,3,'realisation',5,
 'Pose: A salary of Tsh 400,000 has 12.5% deducted for tax and ⅛ saved. Find take-home pay.',
 'Calculate the take-home pay after tax deduction and savings.',
 'Take-home pay correctly calculated as Tsh 300,000. Full working shown.'],

// ── Ch5: Algebra ──────────────────────────────────────────────────────────────

// 164: Use letters to represent unknown quantities
[164,1,'introduction',5,
 'Demonstrate: "I am thinking of a number. When I add 5, I get 12. What is the number?" Show how to write this as x + 5 = 12 and solve.',
 'Watch the demonstration and try to write the word problem as an equation using a letter.',
 'Students can write a simple word problem as an algebraic equation.'],
[164,2,'development',20,
 'Guide groups to translate word problems into algebraic expressions and equations using letters for unknown quantities. Work through a range of examples.',
 'Translate each word problem into an algebraic expression or equation using letters for unknowns.',
 'Word problems are correctly translated into algebraic expressions and equations.'],
[164,9,'design',10,
 'Students write their own word problem involving an unknown quantity and express it algebraically, then swap with a partner to solve.',
 'Write a word problem with an unknown quantity, express it algebraically, and solve a partner\'s problem.',
 'Word problems are correctly expressed algebraically and solved.'],
[164,3,'realisation',5,
 'Write as an equation: "Three times a number decreased by 7 equals 14." Then state what the letter represents.',
 'Write the word problem as an equation and state what the letter represents.',
 'Equation 3x − 7 = 14 (or equivalent) is correctly written and x is correctly defined.'],

// 165: Simplify algebraic expressions by collecting like terms
[165,1,'introduction',5,
 'Demonstrate: Simplify 3x + 2y − x + 4y. Show the step of identifying like terms and collecting them.',
 'Watch the demonstration and identify which terms are like terms.',
 'Students can identify like terms in an algebraic expression.'],
[165,2,'development',20,
 'Guide groups to simplify algebraic expressions by collecting like terms, including expressions with brackets and negative signs. Use a worksheet with increasing complexity.',
 'Simplify each algebraic expression by collecting like terms. Show all steps.',
 'Algebraic expressions are correctly simplified by collecting like terms.'],
[165,9,'design',10,
 'Students simplify expressions in context: a perimeter problem where side lengths are given as algebraic expressions.',
 'Find the perimeter of the shape by simplifying the algebraic expression for total perimeter.',
 'The perimeter is correctly expressed as a simplified algebraic expression.'],
[165,3,'realisation',5,
 'Simplify: 5a + 3b − 2a + b − 4.',
 'Simplify 5a + 3b − 2a + b − 4.',
 'Answer 3a + 4b − 4 is correctly obtained.'],

// 166: Expand and factorise simple algebraic expressions
[166,1,'introduction',5,
 'Demonstrate expanding: 3(2x + 5) = 6x + 15. Then show the reverse — factorising: 6x + 15 = 3(2x + 5). Use area model visual aid.',
 'Watch the demonstration and state in your words what expanding and factorising mean.',
 'Students can explain the relationship between expanding and factorising.'],
[166,2,'development',20,
 'Guide groups to expand brackets and factorise expressions using the highest common factor. Progress from simple to more complex examples.',
 'Expand the given expressions and factorise the given expressions, showing all steps.',
 'Expressions are correctly expanded and factorised with HCF correctly identified.'],
[166,9,'design',10,
 'Students work on individual problems: expand and simplify, then factorise the result to verify.',
 'Expand and simplify each expression, then factorise your answer to check.',
 'Expressions are correctly expanded, simplified and factorised.'],
[166,3,'realisation',5,
 'Expand: 4(3x − 2) + 2(x + 5). Then factorise your answer.',
 'Expand 4(3x − 2) + 2(x + 5) and factorise the result.',
 'Expansion gives 14x − 2; factorised form is 2(7x − 1). Both correctly obtained.'],

// 167: Solve linear equations in one unknown
[167,1,'introduction',5,
 'Demonstrate solving: 3x + 5 = 14. Show the balance method step by step. Verify the solution by substitution.',
 'Watch the demonstration and try to explain each step in the balance method.',
 'Students can use the balance method to solve a simple one-step linear equation.'],
[167,2,'development',20,
 'Guide groups to solve linear equations of increasing complexity: one-step, two-step, equations with brackets, equations with unknowns on both sides.',
 'Solve each linear equation using the balance method. Show all steps and verify your answer.',
 'Linear equations are correctly solved using the balance method with verification shown.'],
[167,9,'design',10,
 'Students solve linear equations in word-problem contexts: age problems, money problems, measurement problems.',
 'Translate each word problem into a linear equation, solve it, and state the answer in context.',
 'Linear equations are correctly solved in context with answers correctly interpreted.'],
[167,3,'realisation',5,
 'Solve: 2(3x − 4) = 5x + 1.',
 'Solve 2(3x − 4) = 5x + 1, showing all steps.',
 'Answer x = 9 is correctly obtained with all steps shown.'],

// 168: Form and solve linear equations from real-life problems
[168,5,'introduction',5,
 'Pose a real-life problem: "Ali has some money. He spends Tsh 3,000 on food and Tsh 1,500 on transport, and has Tsh 2,500 left. How much did he start with?" Ask how to solve using algebra.',
 'Discuss how to write this problem as an equation and solve it.',
 'Students can write and solve a simple real-life linear equation.'],
[168,2,'development',20,
 'Guide groups to form and solve linear equations from real-life scenarios: age problems, consecutive number problems, perimeter problems, work and time problems.',
 'Form linear equations from the given scenarios, solve them, and interpret the answers in context.',
 'Linear equations are correctly formed from real-life scenarios and correctly solved.'],
[168,9,'design',10,
 'Groups design their own real-life linear equation problem and solve a problem from another group.',
 'Create a real-life problem that requires forming and solving a linear equation, then solve another group\'s problem.',
 'Real-life linear equation problems are correctly created and solved.'],
[168,3,'realisation',5,
 'Pose: The sum of two consecutive even numbers is 46. Find the numbers.',
 'Form a linear equation for the problem and solve to find the two consecutive even numbers.',
 'Equation 2n + 2 = 46 (or equivalent) is correctly formed and solved. Numbers 22 and 24 are found.'],

// 169: Substitute values into algebraic formulae
[169,1,'introduction',5,
 'Demonstrate substitution: A = πr². Find A when r = 7 cm (use π ≈ 22/7). Show each step clearly.',
 'Watch the substitution and try the next example: V = lwh, find V when l=5, w=3, h=2.',
 'Students can correctly substitute values into a given formula.'],
[169,2,'development',20,
 'Guide groups to substitute values into common formulae: area and perimeter formulae, speed = distance/time, simple interest I = PRT/100.',
 'Substitute the given values into each formula and calculate the result. State units.',
 'Values are correctly substituted into formulae and results correctly calculated with correct units.'],
[169,9,'design',10,
 'Students substitute values into formulae in real-life contexts: calculate simple interest on a loan, find the area of a field, calculate speed.',
 'Substitute given values into the formulae and calculate the answer to each real-life problem.',
 'Formula substitution is correctly applied in real-life contexts with correct results.'],
[169,3,'realisation',5,
 'Calculate simple interest I = PRT/100 when P = Tsh 50,000, R = 8%, T = 3 years.',
 'Calculate simple interest when P = 50,000, R = 8, T = 3.',
 'Simple interest correctly calculated as Tsh 12,000.'],

// 170: Solve simple inequalities and represent solutions on a number line
[170,1,'introduction',5,
 'Demonstrate: Solve x + 3 < 7. Show that x < 4, then draw the number line with an open circle at 4 and an arrow to the left.',
 'Watch the demonstration and draw the number line representation for x + 3 < 7.',
 'Students can solve a simple inequality and represent the solution on a number line.'],
[170,2,'development',20,
 'Guide groups to solve inequalities with one operation, two operations, and negative coefficients (remembering to flip the inequality sign). Represent solutions on number lines.',
 'Solve each inequality and represent the solution on a number line. Note when to flip the inequality sign.',
 'Inequalities are correctly solved and solutions correctly represented on number lines.'],
[170,9,'design',10,
 'Students solve inequalities in real-life contexts and represent solutions: minimum score needed to pass, maximum items fitting in a box.',
 'Solve the inequality problems in context, state the solution, and represent it on a number line.',
 'Inequalities in context are correctly solved and solution sets correctly represented.'],
[170,3,'realisation',5,
 'Solve and draw a number line: 3x − 5 ≥ 7.',
 'Solve 3x − 5 ≥ 7 and represent the solution on a number line.',
 'Solution x ≥ 4 is correctly obtained and represented with a closed circle at 4 and arrow to the right.'],

// 171: Use algebraic expressions to solve age, money and number problems
[171,5,'introduction',5,
 'Pose: "Kali is 3 years older than Tatu. The sum of their ages is 27. Find each person\'s age." Brainstorm how algebra can help solve this.',
 'Discuss how to represent the unknowns with letters and set up an equation.',
 'Students can set up a linear equation for the age problem.'],
[171,2,'development',20,
 'Guide groups to solve age, money and number word problems using algebraic expressions. Work through a variety of contexts.',
 'Solve the age, money and number problems by forming and solving algebraic equations. Show all working.',
 'Age, money and number problems are correctly solved using algebraic equations.'],
[171,9,'design',10,
 'Students solve individual word problems involving algebra in real-life contexts.',
 'Solve the word problems independently, forming equations and showing all working.',
 'Word problems are correctly solved with equations formed and full working shown.'],
[171,3,'realisation',5,
 'Pose: A father is four times as old as his son. In 6 years, he will be twice as old. Find their current ages.',
 'Form and solve equations to find the current ages of the father and son.',
 'Son is 6, father is 24. Correct equations formed and solved with full working shown.'],

// 172: Introduce simultaneous linear equations (two unknowns)
[172,1,'introduction',5,
 'Demonstrate: "Two items cost a total of Tsh 1,000. One item costs Tsh 200 more than the other. Find the cost of each." Show how to write two equations.',
 'Watch the demonstration and write two equations for the given problem.',
 'Students can write two linear equations to represent a problem with two unknowns.'],
[172,2,'development',20,
 'Guide groups through solving simultaneous equations using the elimination method and substitution method. Work through simple examples with clear steps.',
 'Solve the simultaneous equations using both elimination and substitution methods. Show all steps.',
 'Simultaneous equations are correctly solved using both elimination and substitution methods.'],
[172,9,'design',10,
 'Students solve simultaneous equations from real-life contexts: finding prices of two items, finding two unknown quantities in a mixture.',
 'Solve the simultaneous equation problems in context, showing all working.',
 'Simultaneous equations in context are correctly solved with full working shown.'],
[172,3,'realisation',5,
 'Solve: x + y = 10 and x − y = 4.',
 'Solve the simultaneous equations x + y = 10 and x − y = 4.',
 'x = 7 and y = 3 correctly found using a valid method with full working shown.'],

// 173: Solve word problems using simultaneous equations
[173,7,'introduction',5,
 'Case study: At a school shop, 3 pens and 2 books cost Tsh 1,400. 1 pen and 3 books cost Tsh 1,100. Find the cost of each.',
 'Write equations for the case study and attempt to solve them.',
 'Students correctly write the two equations for the case study.'],
[173,2,'development',20,
 'Guide groups to form and solve simultaneous equations from word problems in various contexts: prices, quantities, ages, mixture problems.',
 'Form and solve simultaneous equations from the given word problems. Interpret the answers in context.',
 'Word problems are correctly translated into simultaneous equations and correctly solved.'],
[173,9,'design',10,
 'Groups create their own simultaneous equation word problem and exchange with another group to solve.',
 'Create a word problem requiring simultaneous equations and solve the problem given by another group.',
 'Word problems requiring simultaneous equations are correctly created and solved.'],
[173,3,'realisation',5,
 'Pose: The sum of two numbers is 35. Their difference is 11. Find the two numbers.',
 'Form and solve simultaneous equations to find the two numbers.',
 'Numbers 23 and 12 correctly found. Equations correctly formed and solved.'],

// 174: Introduce quadratic expressions and equations
[174,1,'introduction',5,
 'Demonstrate expanding: (x + 2)(x + 3) = x² + 5x + 6. Show the FOIL method. Note the highest power is 2 — this is quadratic.',
 'Watch the expansion and try to expand (x + 1)(x + 4) using the same method.',
 'Students can expand a product of two binomials to obtain a quadratic expression.'],
[174,2,'development',20,
 'Guide groups to expand products of binomials and identify quadratic expressions. Also factorize simple quadratic expressions where possible.',
 'Expand the given products and factorise the given quadratic expressions. Show all working.',
 'Products of binomials are correctly expanded and simple quadratic expressions correctly factorised.'],
[174,9,'design',10,
 'Students solve simple quadratic equations by factorisation: x² + 5x + 6 = 0.',
 'Solve the quadratic equations by factorisation. Show all steps including finding the factors.',
 'Quadratic equations are correctly solved by factorisation with all steps shown.'],
[174,3,'realisation',5,
 'Expand (x − 3)(x + 5) and then solve x² + 2x − 15 = 0 by factorisation.',
 'Expand (x − 3)(x + 5) and solve x² + 2x − 15 = 0 by factorisation.',
 'Expansion gives x² + 2x − 15; solutions x = 3 and x = −5 correctly found.'],

// 175: Solve quadratic equations by factorisation
[175,1,'introduction',5,
 'Demonstrate: Solve x² − 5x + 6 = 0 by factorising. Show finding two numbers that multiply to 6 and add to −5.',
 'Watch the demonstration and try to factorise x² + 7x + 12.',
 'Students can find two numbers that satisfy both conditions for simple factorisation.'],
[175,2,'development',20,
 'Guide groups to solve quadratic equations by factorisation, including equations where the coefficient of x² is 1 and then greater than 1.',
 'Solve each quadratic equation by factorisation. Show the factorised form before finding solutions.',
 'Quadratic equations are correctly solved by factorisation with both solutions found.'],
[175,9,'design',10,
 'Students solve quadratic equations in real-life contexts: an area problem (find the length of a rectangle given quadratic area expression), a projectile problem.',
 'Solve the real-life quadratic problems by forming and solving quadratic equations.',
 'Quadratic equations in context are correctly formed and solved by factorisation.'],
[175,3,'realisation',5,
 'Solve: 2x² + 5x − 3 = 0.',
 'Solve 2x² + 5x − 3 = 0 by factorisation.',
 'Solutions x = ½ and x = −3 correctly found by factorisation with full working.'],

// 176: Apply algebra to geometric problems (perimeter, area, angles)
[176,1,'introduction',5,
 'Demonstrate: The perimeter of a rectangle is 36 cm. The length is (2x + 1) cm and width is (x − 1) cm. Find x. Show how to set up and solve the equation.',
 'Watch the demonstration and write the equation for the perimeter problem.',
 'Students can form a linear equation from a geometric perimeter problem.'],
[176,2,'development',20,
 'Guide groups to apply algebra to geometric problems: finding missing angles using algebraic expressions, finding dimensions using area and perimeter equations.',
 'Solve the geometric problems by forming algebraic equations. Show all working and state answers with units.',
 'Algebra is correctly applied to geometric problems with correct equations formed and solved.'],
[176,9,'design',10,
 'Students work on geometry problems involving algebra: angles in a triangle expressed algebraically sum to 180°; sides of a polygon expressed algebraically.',
 'Solve the angle and polygon problems using algebra. Show all equations formed.',
 'Angle and polygon problems are correctly solved using algebraic equations.'],
[176,3,'realisation',5,
 'The angles of a triangle are x°, (2x + 10)° and (3x − 4)°. Find each angle.',
 'Form and solve an equation to find each angle of the triangle.',
 'x = 29; angles 29°, 68°, 83° correctly found. Equation correctly formed using sum = 180°.'],

// 177: Use algebraic graphs to represent linear equations
[177,1,'introduction',5,
 'Demonstrate: Draw the graph of y = 2x + 1 by creating a table of values for x = −2, −1, 0, 1, 2. Plot points and draw the line.',
 'Watch the demonstration and try to create a table of values for y = x + 3.',
 'Students can create a table of values and plot points for a linear equation.'],
[177,2,'development',20,
 'Guide groups to draw graphs of linear equations: identify gradient and y-intercept from the equation, create a table of values, plot points, and draw the line.',
 'Draw graphs of the given linear equations. Create tables of values and label axes, gradient and y-intercept.',
 'Linear equations are correctly graphed with axes labelled, tables of values correct, and gradient and intercept identified.'],
[177,9,'design',10,
 'Students draw graphs of two simultaneous linear equations on the same axes and read off the solution from the graph.',
 'Draw graphs of both equations on the same axes and read the solution (intersection point) from the graph.',
 'Graphs are correctly drawn and the intersection point (solution) is correctly read from the graph.'],
[177,3,'realisation',5,
 'Draw the graph of y = −x + 4 for x values from −1 to 5. State the gradient and y-intercept.',
 'Draw the graph of y = −x + 4, create a table of values, and state the gradient and y-intercept.',
 'Graph correctly drawn; gradient = −1 and y-intercept = 4 correctly stated.'],

// 178: Interpret algebraic graphs in real-life contexts
[178,7,'introduction',5,
 'Present a distance-time graph. Ask students to read the speed from the graph and interpret what happens during each section of the journey.',
 'Read the distance-time graph and describe what is happening at each stage of the journey.',
 'Students can read a distance-time graph and identify speed from its gradient.'],
[178,2,'development',20,
 'Guide groups to interpret graphs in real-life contexts: distance-time (speed), cost-quantity (unit price), temperature-time (rate of cooling/heating). Identify gradient, intercept and what they mean.',
 'Interpret the real-life graphs provided: describe what the gradient and intercept represent in context.',
 'Real-life graphs are correctly interpreted with gradient and intercept correctly explained in context.'],
[178,9,'design',10,
 'Groups draw and interpret their own real-life graph: a water tank filling over time, cost of taxi ride vs. distance, temperature change during the day.',
 'Draw a real-life graph and write an interpretation of the gradient and intercept in context.',
 'Real-life graph is correctly drawn and gradient and intercept correctly interpreted in context.'],
[178,3,'realisation',5,
 'Given a cost graph showing fixed cost of Tsh 5,000 and variable cost of Tsh 500 per unit, write the equation and interpret gradient and y-intercept.',
 'Write the equation for the cost graph and interpret the gradient and y-intercept in context.',
 'Equation C = 500n + 5,000 correctly written; gradient (Tsh 500/unit) and y-intercept (Tsh 5,000 fixed cost) correctly interpreted.'],

];

$db->beginTransaction();
try {
    $count = 0;
    foreach ($data as $r) { $ins->execute($r); $count++; }
    $db->commit();
    echo "Inserted $count element_methods rows for Mathematics.\n";
} catch (Exception $e) {
    $db->rollBack();
    echo "ERROR: " . $e->getMessage() . "\n";
}
