<?php
// Seed element_methods for Business Studies Form I (elements 75-94)
require __DIR__ . '/../config/db.php';
$db = getDB();
$db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

// method_ids: 5=Brainstorming,7=Case Study,1=Demonstration,11=Field Visit,
// 2=Group Discussion,4=Hands-on,9=Practical,8=Project,3=Q&A,12=Research,10=Role Play,6=Think-Pair-Share
$ins = $db->prepare("INSERT INTO element_methods
    (element_id,method_id,stage,time_minutes,teaching_activity,learning_activity,assessment_criteria)
    VALUES (?,?,?,?,?,?,?)");

$data = [

// ── Chapter 1: Introduction to Business Studies ──────────────────────────────

// 75: Define and explain the concept of a business
[75,3,'introduction',5,
 'Display pictures showing various business activities (shop, farm, factory). Ask students: What is a business? Where do you see businesses in your daily life?',
 'Observe the pictures and respond to questions about businesses they see in their community.',
 'Students can identify examples of businesses from their surroundings.'],
[75,2,'development',20,
 'Provide handouts and guide students in groups to explore a scenario showing production, distribution and consumption activities. Guide them to derive the meaning and scope of a business from the scenario.',
 'Read the scenario and handouts, discuss in groups, and share findings on the meaning, characteristics and scope of a business.',
 'The concept and scope of a business are clearly described with correct examples.'],
[75,2,'design',10,
 'Guide groups to draw a simple diagram showing how a business connects producers, distributors and consumers in their community.',
 'In groups, create a diagram linking production, distribution and consumption with a real local business example.',
 'A diagram correctly showing the business cycle is produced and explained.'],
[75,3,'realisation',5,
 'Each student states one definition of a business and one example from their community.',
 'Individually write a one-sentence definition of a business and give one local example.',
 'A correct definition of a business is given with an appropriate example.'],

// 76: Identify and describe characteristics of a business
[76,5,'introduction',5,
 'Brainstorm: Ask students — What makes something a business? List responses on the board.',
 'Call out characteristics they think define a business based on prior knowledge.',
 'Students can suggest at least two characteristics of a business.'],
[76,2,'development',20,
 'Guide students in groups using handouts to identify and describe key characteristics of a business: profit motive, regular dealings, risk, economic activity, exchange of goods/services.',
 'Discuss in groups, compare characteristics, and prepare a summary to share with the class.',
 'Key characteristics of a business are correctly identified and described.'],
[76,6,'design',10,
 'Think-Pair-Share: Each student thinks of a business activity and identifies which characteristics apply, then shares with a partner and then the class.',
 'Identify characteristics of a chosen business, pair up to compare findings, then share with class.',
 'Characteristics of a business are applied correctly to a given example.'],
[76,3,'realisation',5,
 'Ask each student to write 3 key characteristics of a business on a card.',
 'Write 3 characteristics of a business independently.',
 'Three correct characteristics of a business are stated by each student.'],

// 77: Classify types of businesses with examples
[77,5,'introduction',5,
 'Ask students to name all types of businesses they know in their area. Record on board.',
 'Name businesses they know and attempt to group them by type.',
 'Students suggest at least two different types of businesses.'],
[77,2,'development',20,
 'Guide students to classify businesses by type (manufacturing, trading, service), by size (small, medium, large) and by form of ownership. Provide examples of each.',
 'In groups, classify a list of given businesses into the correct categories with justification.',
 'Types of businesses are correctly classified with appropriate examples.'],
[77,4,'design',10,
 'Provide each group with business cards (names of businesses). Groups sort them into categories and justify their classification.',
 'Sort business cards into correct categories: manufacturing, trading or service. Justify each placement.',
 'Businesses are correctly sorted into appropriate categories with reasons.'],
[77,3,'realisation',5,
 'Ask students to draw a simple classification chart for types of businesses individually.',
 'Draw a classification chart showing at least 3 types of businesses with one example each.',
 'A classification chart with correct types and examples is produced.'],

// 78: Define and use key terminologies in Business Studies
[78,3,'introduction',5,
 'Display a list of business terms on the board (profit, capital, revenue, demand, supply). Ask: Which of these terms do you already know?',
 'Identify terms they recognise and share their understanding with the class.',
 'Students show prior knowledge of at least 2 business terms.'],
[78,2,'development',20,
 'Provide handouts with definitions of key business terminologies. Guide groups to match terms with definitions and use each in a business sentence.',
 'Read definitions, match terms to meanings in groups, and construct sentences using each term correctly.',
 'Key business terminologies are correctly defined and used in sentences.'],
[78,6,'design',10,
 'Think-Pair-Share: Each student is given 3 terms; they write definitions, compare with a partner and correct each other.',
 'Write definitions of assigned terms, compare with partner, and agree on correct definitions.',
 'Business terminologies are accurately defined after peer review.'],
[78,3,'realisation',5,
 'Quiz: Ask 5 quick-fire questions using business terms. Students answer individually.',
 'Answer 5 questions using correct business terminologies.',
 'At least 4 out of 5 business terminologies are used correctly in answers.'],

// 79: Explain the importance of business terminologies in practice
[79,3,'introduction',5,
 'Ask students: What would happen if a buyer and seller used different meanings for the word "profit"? Why does language matter in business?',
 'Discuss why using correct terms matters in business communication.',
 'Students articulate at least one reason why terminology matters in business.'],
[79,2,'development',20,
 'Guide class discussion on how correct terminologies help in business communication, record keeping, negotiation, legal compliance, and management decision-making.',
 'Participate in discussion and take notes on the importance of terminologies in specific business situations.',
 'The importance of business terminologies in practice is explained with relevant examples.'],
[79,10,'design',10,
 'Role play: Assign pairs to simulate a buyer-seller negotiation using correct business terms. Observe and give feedback.',
 'Role-play a business negotiation using at least 5 correct business terms.',
 'Correct business terminologies are used appropriately in the role-play scenario.'],
[79,3,'realisation',5,
 'Students write two sentences explaining why terminologies are important in running a business.',
 'Write two sentences explaining the practical importance of business terminologies.',
 'The importance of business terminologies is explained correctly in own words.'],

// 80: Describe the scope and nature of Business Studies as a subject
[80,5,'introduction',5,
 'Show video clips or images of various business activities. Ask: What does Business Studies cover as a school subject?',
 'Watch/observe and suggest what topics Business Studies might cover.',
 'Students can suggest at least 2 areas covered by Business Studies.'],
[80,2,'development',20,
 'Guide students through jigsaw to explore the scope of Business Studies: production, marketing, finance, human resources, entrepreneurship. Each group covers one area and teaches others.',
 'In jigsaw groups, research one area of Business Studies and present findings to peers.',
 'The scope of Business Studies is described accurately covering at least 4 areas.'],
[80,4,'design',10,
 'Groups create a mind map on paper showing the scope of Business Studies and how the areas connect.',
 'Create a mind map linking all major areas of Business Studies.',
 'A mind map correctly showing the scope of Business Studies is produced.'],
[80,3,'realisation',5,
 'Each student describes the scope of Business Studies in two sentences.',
 'Write two sentences describing what Business Studies covers as a subject.',
 'The scope and nature of Business Studies is described correctly.'],

// 81: Explain the importance and relevance of Business Studies
[81,5,'introduction',5,
 'Brainstorm: Ask students why they are studying Business Studies and what they hope to gain from it.',
 'Share personal reasons for studying Business Studies and listen to classmates\' responses.',
 'Students articulate personal relevance of Business Studies.'],
[81,2,'development',20,
 'Guide discussion on the importance of Business Studies: career development, entrepreneurship, daily life applications (budgeting, managing money, consumer awareness).',
 'Participate in group discussion and compile a list of 5 reasons why Business Studies is important.',
 'The importance and relevance of Business Studies is explained with specific examples.'],
[81,11,'design',10,
 'Invite a resourceful person (local business owner or accountant) to share how Business Studies knowledge helped them. Students ask questions.',
 'Listen to guest speaker and ask at least one question. Note key points from the presentation.',
 'Students can explain how Business Studies is relevant to real careers and daily life.'],
[81,3,'realisation',5,
 'Each student writes 3 reasons why Business Studies is important to them personally.',
 'Write 3 reasons why Business Studies is personally important and relevant.',
 'Three valid reasons for the importance of Business Studies are given.'],

// 82: Identify career opportunities related to Business Studies
[82,5,'introduction',5,
 'Ask: What jobs can you get by studying Business Studies? Record all suggestions on the board.',
 'Suggest career paths they associate with Business Studies.',
 'Students suggest at least 3 career options related to Business Studies.'],
[82,12,'development',20,
 'Guide students in groups to research career opportunities in Business Studies: accountant, marketing officer, entrepreneur, banker, business consultant, supply chain manager, tax officer.',
 'Research and compile a list of career opportunities in Business Studies with brief descriptions of each role.',
 'At least 5 career opportunities related to Business Studies are correctly identified and described.'],
[82,2,'design',10,
 'Groups present their career findings. Class discusses qualifications needed for each career.',
 'Present career findings and discuss with class what qualifications each career requires.',
 'Career opportunities related to Business Studies are presented with relevant qualifications.'],
[82,3,'realisation',5,
 'Each student names 3 career opportunities in Business Studies and describes the role in one sentence each.',
 'Write 3 career opportunities with a one-sentence description of each.',
 'Three career opportunities in Business Studies are correctly described.'],

// ── Chapter 2: Entrepreneurship ──────────────────────────────────────────────

// 83: Define and explain the concept of entrepreneurship
[83,5,'introduction',5,
 'Brainstorm: Guide students to list different activities performed by people in their community and what it takes to do them successfully.',
 'Name community activities and discuss what skills and qualities are needed to do them successfully.',
 'Students connect community activities to the qualities of an entrepreneur.'],
[83,2,'development',20,
 'Guide students through group discussion on the meaning, characteristics, skills and importance of entrepreneurship, using handouts and video clips of successful entrepreneurs.',
 'Discuss in groups and compile notes on the meaning of entrepreneurship and characteristics of a successful entrepreneur.',
 'The concept of entrepreneurship is clearly defined with correct characteristics and importance.'],
[83,11,'design',10,
 'Field trip debrief or video analysis: Guide students to analyse a local entrepreneur\'s story, identifying which entrepreneurship qualities they demonstrated.',
 'Analyse a real entrepreneur\'s story, identifying characteristics and skills that made them successful.',
 'Entrepreneurial characteristics are correctly identified from a real-life example.'],
[83,3,'realisation',5,
 'Each student writes a definition of entrepreneurship and names 3 characteristics of a successful entrepreneur.',
 'Write a definition of entrepreneurship and list 3 characteristics of an entrepreneur.',
 'Entrepreneurship is correctly defined and 3 characteristics are accurately stated.'],

// 84: Identify and describe characteristics of a successful entrepreneur
[84,3,'introduction',5,
 'Show pictures of successful Tanzanian entrepreneurs (e.g., business leaders). Ask: What makes these people successful?',
 'Observe pictures and suggest qualities that make these individuals successful entrepreneurs.',
 'Students can identify at least 2 characteristics of successful entrepreneurs from observation.'],
[84,2,'development',20,
 'Guide groups to identify and discuss the key characteristics of a successful entrepreneur: risk-taking, innovation, creativity, leadership, persistence, decision-making, communication.',
 'In groups, research and discuss characteristics of successful entrepreneurs and prepare a presentation.',
 'Key characteristics of a successful entrepreneur are correctly identified and described.'],
[84,7,'design',10,
 'Case study: Provide case studies of successful and unsuccessful entrepreneurs. Groups identify which characteristics were present or absent.',
 'Analyse case studies and identify which entrepreneurial characteristics contributed to success or failure.',
 'Entrepreneurial characteristics are correctly applied in case study analysis.'],
[84,3,'realisation',5,
 'Ask students to rank the 3 most important characteristics of an entrepreneur and justify their ranking.',
 'Rank 3 entrepreneurial characteristics in order of importance and justify the ranking.',
 'Top 3 entrepreneurial characteristics are ranked with a valid justification.'],

// 85: Explain the importance of entrepreneurship in economic development
[85,3,'introduction',5,
 'Ask students: How do businesses help our community and country? What happens when many people start businesses?',
 'Discuss how businesses they know contribute to the community.',
 'Students identify at least 2 ways businesses benefit the community.'],
[85,2,'development',20,
 'Guide discussion on the role of entrepreneurship in economic development: job creation, production of goods and services, generating government revenue, innovation, poverty reduction.',
 'Participate in group discussion and compile a list of ways entrepreneurship contributes to economic development.',
 'The importance of entrepreneurship in economic development is explained with specific examples.'],
[85,4,'design',10,
 'Groups create a diagram showing how entrepreneurship contributes to Tanzania\'s economic development, linking entrepreneur → business → jobs → taxes → development.',
 'Create a diagram showing the chain of how entrepreneurship drives economic development.',
 'A diagram correctly showing entrepreneurship\'s contribution to economic development is produced.'],
[85,3,'realisation',5,
 'Each student explains in writing two specific ways entrepreneurship contributes to Tanzania\'s economic development.',
 'Write two specific ways entrepreneurship contributes to Tanzania\'s economy.',
 'Two valid contributions of entrepreneurship to economic development are stated correctly.'],

// 86: Describe the major theories of entrepreneurship
[86,3,'introduction',5,
 'Present names of the main entrepreneurship theories: Innovation Theory, Economic Theory, Sociological Theory, Opportunity-Based Theory. Ask what students think each theory says.',
 'Predict what each theory might be about based on its name.',
 'Students show curiosity and make logical predictions about entrepreneurship theories.'],
[86,10,'development',20,
 'Guide groups to simulate/role-play scenarios representing different theories of entrepreneurship. Each group acts out one theory and explains it to the class.',
 'Prepare and perform a role-play representing an assigned entrepreneurship theory. Explain the theory to classmates.',
 'Major theories of entrepreneurship are correctly described through role play and explanation.'],
[86,2,'design',10,
 'Groups compare the theories: What does each say drives entrepreneurship? Where do they agree or differ?',
 'Compare assigned theories and identify key similarities and differences.',
 'Similarities and differences between entrepreneurship theories are correctly identified.'],
[86,3,'realisation',5,
 'Each student describes two theories of entrepreneurship in their own words.',
 'Write brief descriptions of two entrepreneurship theories in own words.',
 'Two theories of entrepreneurship are correctly described.'],

// 87: Apply entrepreneurship theories to analyse business situations
[87,7,'introduction',5,
 'Present a brief case study of a Tanzanian entrepreneur. Ask: Which theory do you think best explains why this person became an entrepreneur?',
 'Read the case study and suggest which entrepreneurship theory applies and why.',
 'Students attempt to link a business case to an entrepreneurship theory.'],
[87,7,'development',20,
 'Provide case studies of different Tanzanian businesses. Guide groups to analyse each using a specific entrepreneurship theory and present their analysis.',
 'Analyse assigned case studies using entrepreneurship theories and prepare a group presentation.',
 'Entrepreneurship theories are correctly applied to analyse given business situations.'],
[87,2,'design',10,
 'Groups debate which entrepreneurship theory best explains the success of local businesses in Tanzania.',
 'Participate in a structured debate on which theory best explains Tanzanian entrepreneurship.',
 'Students demonstrate ability to evaluate and defend the application of entrepreneurship theories.'],
[87,3,'realisation',5,
 'Each student writes a short analysis of a given business situation using one entrepreneurship theory.',
 'Write a short paragraph analysing a business situation using one specific theory of entrepreneurship.',
 'An entrepreneurship theory is correctly applied to analyse a given business situation.'],

// 88: Evaluate the relevance of entrepreneurship theories in Tanzania
[88,2,'introduction',5,
 'Ask: Do theories developed in other countries fully apply to businesses in Tanzania? What might be different here?',
 'Discuss the local business environment and how it might differ from where theories were developed.',
 'Students identify at least one contextual difference that could affect theory relevance.'],
[88,2,'development',20,
 'Guide critical group discussion on the relevance and limitations of each entrepreneurship theory in the Tanzanian context (cultural factors, economic conditions, regulatory environment).',
 'Discuss in groups the applicability of entrepreneurship theories to the Tanzanian business environment.',
 'The relevance of entrepreneurship theories to the Tanzanian context is critically evaluated.'],
[88,2,'design',10,
 'Each group evaluates one theory\'s relevance to Tanzania and presents strengths and weaknesses.',
 'Evaluate the relevance of an assigned theory in Tanzania and present findings.',
 'Strengths and limitations of each entrepreneurship theory in the Tanzanian context are correctly identified.'],
[88,3,'realisation',5,
 'Each student writes their evaluation of one theory\'s relevance to entrepreneurship in Tanzania.',
 'Write an evaluation of one entrepreneurship theory\'s relevance in the Tanzanian context.',
 'A balanced evaluation of an entrepreneurship theory\'s relevance to Tanzania is provided.'],

// ── Chapter 3: Sole Proprietorship ───────────────────────────────────────────

// 89: Define and describe the concept of sole proprietorship
[89,5,'introduction',5,
 'Brainstorm: Guide students to identify businesses in their community owned by one person. Ask why some businesses are owned by one person and others by more.',
 'Name businesses owned by one person in their community and suggest why someone might run a business alone.',
 'Students identify examples of sole proprietor businesses from their surroundings.'],
[89,2,'development',20,
 'Guide group discussion on the concept, meaning and features of sole proprietorship. Supplement with a guest speaker (sole proprietor) sharing their experience.',
 'Discuss the meaning and features of sole proprietorship, listen to guest speaker, and take notes.',
 'The concept of sole proprietorship is clearly defined with correct features.'],
[89,2,'design',10,
 'Groups draw a comparison chart between sole proprietorship and other forms of business ownership they know.',
 'Create a comparison chart showing how sole proprietorship differs from other forms of business.',
 'Sole proprietorship is correctly distinguished from other forms of business ownership.'],
[89,3,'realisation',5,
 'Students write a definition of sole proprietorship and list 3 features.',
 'Write a definition of sole proprietorship and list 3 key features.',
 'Sole proprietorship is correctly defined with 3 accurate features.'],

// 90: Identify advantages and disadvantages of sole proprietorship
[90,3,'introduction',5,
 'Ask: What are the good things and bad things about running a business completely on your own?',
 'Share perceived advantages and disadvantages of running a business alone.',
 'Students can suggest at least 2 advantages and 2 disadvantages of operating alone.'],
[90,2,'development',20,
 'Guide discussion on advantages (full control, all profits retained, quick decisions, simple to form, privacy) and disadvantages (unlimited liability, limited capital, no continuity, all risks) of sole proprietorship.',
 'Discuss and compile a list of advantages and disadvantages of sole proprietorship.',
 'Advantages and disadvantages of sole proprietorship are correctly identified and explained.'],
[90,7,'design',10,
 'Case study: Students analyse a given sole proprietor business scenario and identify which advantages and disadvantages are evident.',
 'Analyse a case study of a sole proprietor and identify advantages and disadvantages experienced.',
 'Advantages and disadvantages of sole proprietorship are correctly applied to a case study.'],
[90,4,'realisation',5,
 'Each student creates a T-chart listing 3 advantages and 3 disadvantages of sole proprietorship.',
 'Create a T-chart with 3 advantages and 3 disadvantages of sole proprietorship.',
 'A T-chart with 3 correct advantages and 3 correct disadvantages of sole proprietorship is produced.'],

// 91: Describe the steps and legal requirements for forming a sole proprietorship
[91,3,'introduction',5,
 'Ask: What steps would you take to start your own business legally in Tanzania? What documents might you need?',
 'Suggest steps they think are needed to start a legal business.',
 'Students attempt to outline basic steps for starting a business.'],
[91,2,'development',20,
 'Guide students to describe the steps for forming a sole proprietorship in Tanzania: develop business idea → source capital → choose business name → register with BRELA → obtain trading licence → open bank account.',
 'Discuss and document the steps and legal requirements for forming a sole proprietorship using BRELA resources.',
 'The steps and legal requirements for forming a sole proprietorship in Tanzania are correctly described.'],
[91,8,'design',10,
 'Project activity: Groups write a simple report on how to register a sole proprietorship in Tanzania, including required documents and costs.',
 'Write a group report outlining the registration process and legal requirements for a sole proprietorship.',
 'A report correctly detailing the steps for forming a sole proprietorship is produced.'],
[91,3,'realisation',5,
 'Each student outlines the 4 main steps for forming a sole proprietorship in the correct order.',
 'List the 4 main steps for forming a sole proprietorship in the correct sequence.',
 'The 4 main steps for forming a sole proprietorship are listed correctly and in order.'],

// 92: Identify sources of capital for a sole proprietor
[92,5,'introduction',5,
 'Ask: Where does the money come from to start a business? If you had no money, how would you start?',
 'Suggest possible sources of money for starting a business.',
 'Students identify at least 2 sources of start-up capital.'],
[92,2,'development',20,
 'Guide students to identify and describe various sources of capital: personal savings, loans from family/friends, bank loans, microfinance institutions, SACCOS, government grants.',
 'In groups, research and discuss sources of capital available to sole proprietors in Tanzania.',
 'At least 4 sources of capital for a sole proprietor are correctly identified and described.'],
[92,2,'design',10,
 'Groups evaluate the best sources of capital for a small business in their local area, considering accessibility, cost and risk.',
 'Evaluate and rank sources of capital by suitability for a small sole proprietor business in the local area.',
 'Sources of capital are evaluated with valid criteria and ranked appropriately.'],
[92,3,'realisation',5,
 'Each student lists 4 sources of capital and explains one advantage of each source.',
 'List 4 sources of capital with one advantage for each.',
 'Four sources of capital are listed with a correct advantage stated for each.'],

// 93: Identify challenges facing sole proprietorship businesses
[93,7,'introduction',5,
 'Present a short case study of a struggling sole proprietor. Ask: What problems is this business facing?',
 'Read the case study and identify problems facing the business.',
 'Students identify at least 2 challenges from the case study.'],
[93,2,'development',20,
 'Guide groups to identify and discuss common challenges: limited capital, unlimited liability, heavy workload, competition, lack of managerial skills, market access, government regulations.',
 'In groups, identify and discuss challenges facing sole proprietorship businesses and prepare a summary.',
 'Key challenges facing sole proprietorship businesses are correctly identified and explained.'],
[93,2,'design',10,
 'Groups categorise the challenges into financial, managerial and market-related and present their categorisation.',
 'Categorise identified challenges into financial, managerial and market-related groups.',
 'Challenges are correctly categorised into appropriate groups with justification.'],
[93,3,'realisation',5,
 'Each student identifies and briefly describes 3 challenges facing a sole proprietorship.',
 'Write 3 challenges facing sole proprietorship businesses with a brief explanation of each.',
 'Three challenges facing sole proprietorship are correctly identified and described.'],

// 94: Propose and evaluate solutions to challenges facing sole proprietors
[94,5,'introduction',5,
 'Refer to the case study from the previous lesson. Ask: How can the sole proprietor solve the problems identified?',
 'Suggest possible solutions to the challenges identified in the case study.',
 'Students suggest at least 2 practical solutions to challenges facing a sole proprietor.'],
[94,2,'development',20,
 'Guide students to brainstorm and discuss practical solutions: joining SACCO, seeking microfinance, employing staff, marketing strategies, business training, forming partnerships.',
 'Brainstorm and discuss solutions to each challenge. Evaluate which solutions are most practical.',
 'Practical solutions to challenges facing sole proprietors are proposed and justified.'],
[94,8,'design',10,
 'Groups develop a simple action plan with specific solutions for each challenge, evaluating the effectiveness of each solution.',
 'Create a group action plan proposing solutions to 3 challenges with evaluation of effectiveness.',
 'An action plan with feasible solutions and evaluation is produced.'],
[94,3,'realisation',5,
 'Each student writes a brief action plan proposing solutions to 3 challenges facing a sole proprietor.',
 'Write an action plan with solutions to 3 challenges facing a sole proprietor.',
 'An action plan with 3 valid solutions to sole proprietorship challenges is produced.'],

];

$db->beginTransaction();
try {
    $count = 0;
    foreach ($data as $r) {
        $ins->execute($r);
        $count++;
    }
    $db->commit();
    echo "Inserted $count element_methods rows for Business Studies.\n";
} catch (Exception $e) {
    $db->rollBack();
    echo "ERROR: " . $e->getMessage() . "\n";
}
